import { defineExample } from "./define-example.js";

export const youtubeTopKExample = defineExample({
  id: "youtube-top-k",
  name: "YouTube Top K Videos",
  difficulty: "hard",
  description: "Count-min sketch and heap-based top-K trending videos at massive scale.",
  tags: ["streaming", "top-k", "approximation"],
  patternsUsed: ["count-min-sketch", "min-heap", "lambda-aggregation"],
  layoutHint: "pipeline",
  defaultScenarioId: "ytk-view",
  columns: [
    ["Client"],
    ["ViewGateway"],
    ["ViewStream"],
    ["ViewAggregator", "BatchWorker"],
    ["CountMinSketch", "TopKHeap", "TrendingDB"],
  ],
  nodes: [
    { id: "Client", kind: "external", label: "Client" },
    { id: "ViewGateway", kind: "gateway", label: "View Gateway" },
    { id: "ViewAggregator", kind: "service", label: "View Aggregator", icon: "microservice" },
    { id: "CountMinSketch", kind: "database", label: "Count-Min Sketch", icon: "redis" },
    { id: "TopKHeap", kind: "database", label: "Top-K Heap", icon: "redis" },
    { id: "TrendingDB", kind: "database", label: "Trending DB", icon: "postgres" },
    { id: "ViewStream", kind: "queue", label: "View Stream", icon: "kafka" },
    { id: "BatchWorker", kind: "service", label: "Batch Worker", icon: "microservice" },
  ],
  channels: [
    { id: "ch-view", source: "Client", target: "ViewGateway", label: "record view", delivery: "async", relationship: "event", payloadKind: "event" },
    { source: "ViewGateway", target: "ViewStream", label: "emit event", delivery: "async", relationship: "event", payloadKind: "event" },
    { id: "ch-aggregate", source: "ViewStream", target: "ViewAggregator", label: "consume", delivery: "async", relationship: "event", payloadKind: "event" },
    { id: "ch-sketch", source: "ViewAggregator", target: "CountMinSketch", label: "increment", delivery: "sync", relationship: "command", payloadKind: "command" },
    { id: "ch-heap", source: "ViewAggregator", target: "TopKHeap", label: "update heap", delivery: "sync", relationship: "command", payloadKind: "command" },
    { id: "ch-persist", source: "BatchWorker", target: "TrendingDB", label: "flush top-k", delivery: "sync", relationship: "command", payloadKind: "command" },
    { source: "ViewStream", target: "BatchWorker", label: "batch", delivery: "async", relationship: "event", payloadKind: "event" },
  ],
  scenarios: [
    { id: "ytk-view", name: "Record View", steps: [
      { name: "View Event", channelId: "ch-view", fromNode: "Client", payloadType: "ViewEvent", payloadData: { videoId: "v1" } },
      { name: "Update Sketch", channelId: "ch-sketch", fromNode: "ViewAggregator", payloadType: "Increment", payloadData: { videoId: "v1" } },
      { name: "Update Heap", channelId: "ch-heap", fromNode: "ViewAggregator", payloadType: "HeapUpdate", payloadData: { videoId: "v1" } },
    ]},
    { id: "ytk-query", name: "Query Top K", steps: [
      { name: "Read Heap", description: "Return top 10 trending videos", visuals: [{ kind: "signal", targetId: "TopKHeap", color: "green" }] },
      { name: "Fallback DB", channelId: "ch-persist", fromNode: "BatchWorker", payloadType: "GetTopK", payloadData: { k: 10 } },
    ]},
    { id: "ytk-batch", name: "Batch Flush", steps: [
      { name: "Periodic Flush", description: "Worker persists heap to DB every minute", visuals: [{ kind: "lag", targetId: "BatchWorker", color: "yellow" }] },
    ]},
  ],
});

export const uberExample = defineExample({
  id: "uber",
  name: "Uber",
  difficulty: "hard",
  description: "Ride matching with geospatial indexing, surge pricing, and real-time tracking.",
  tags: ["geo", "matching", "surge-pricing"],
  patternsUsed: ["quad-tree-index", "supply-demand", "websocket-tracking"],
  layoutHint: "hub",
  defaultScenarioId: "uber-request",
  columns: [
    ["RiderApp", "DriverApp"],
    ["TripGateway", "LocationStream"],
    ["MatchingService", "PricingService", "LocationService"],
    ["TripDB", "GeoIndex", "SurgeCache"],
  ],
  nodes: [
    { id: "RiderApp", kind: "external", label: "Rider App" },
    { id: "DriverApp", kind: "external", label: "Driver App" },
    { id: "TripGateway", kind: "gateway", label: "Trip Gateway" },
    { id: "MatchingService", kind: "service", label: "Matching Service", icon: "microservice" },
    { id: "PricingService", kind: "service", label: "Pricing Service", icon: "microservice" },
    { id: "LocationService", kind: "service", label: "Location Service", icon: "microservice" },
    { id: "TripDB", kind: "database", label: "Trip DB", icon: "postgres" },
    { id: "GeoIndex", kind: "database", label: "Geo Index", icon: "mongodb" },
    { id: "SurgeCache", kind: "database", label: "Surge Cache", icon: "redis" },
    { id: "LocationStream", kind: "queue", label: "Location Stream", icon: "kafka" },
  ],
  channels: [
    { id: "ch-request", source: "RiderApp", target: "TripGateway", label: "request ride", delivery: "sync", relationship: "command", payloadKind: "command" },
    { id: "ch-match", source: "TripGateway", target: "MatchingService", label: "find driver", delivery: "sync", relationship: "command", payloadKind: "command" },
    { id: "ch-geo", source: "MatchingService", target: "GeoIndex", label: "nearby drivers", delivery: "sync", relationship: "query", payloadKind: "query" },
    { id: "ch-surge", source: "MatchingService", target: "PricingService", label: "get fare", delivery: "sync", relationship: "query", payloadKind: "query" },
    { source: "PricingService", target: "SurgeCache", label: "surge multiplier", delivery: "sync", relationship: "query", payloadKind: "query" },
    { source: "MatchingService", target: "TripDB", label: "create trip", delivery: "sync", relationship: "command", payloadKind: "command" },
    { id: "ch-gps", source: "DriverApp", target: "LocationStream", label: "GPS stream", delivery: "async", relationship: "event", payloadKind: "event" },
    { source: "LocationStream", target: "LocationService", label: "update", delivery: "async", relationship: "event", payloadKind: "event" },
    { source: "LocationService", target: "GeoIndex", label: "GEOADD", delivery: "sync", relationship: "command", payloadKind: "command" },
    { source: "MatchingService", target: "DriverApp", label: "ride offer", delivery: "sync", relationship: "event", payloadKind: "event" },
    { source: "TripGateway", target: "RiderApp", label: "track trip", delivery: "sync", relationship: "event", payloadKind: "event" },
  ],
  scenarios: [
    { id: "uber-request", name: "Request Ride", steps: [
      { name: "Request", channelId: "ch-request", fromNode: "RiderApp", payloadType: "RequestRide", payloadData: { pickup: "A", dropoff: "B" } },
      { name: "Find Driver", channelId: "ch-match", fromNode: "TripGateway", payloadType: "MatchDriver", payloadData: {} },
      { name: "Geo Query", channelId: "ch-geo", fromNode: "MatchingService", payloadType: "NearbyDrivers", payloadData: { radius: "2km" } },
    ]},
    { id: "uber-surge", name: "Surge Pricing", steps: [
      { name: "High Demand", channelId: "ch-surge", fromNode: "MatchingService", payloadType: "CalculateFare", payloadData: { zone: "downtown" } },
      { name: "2x Surge", visuals: [{ kind: "highlight", targetId: "SurgeCache", color: "yellow", label: "2.0x" }] },
    ]},
    { id: "uber-track", name: "Live Tracking", steps: [
      { name: "GPS Update", channelId: "ch-gps", fromNode: "DriverApp", payloadType: "GPSUpdate", payloadData: { lat: 37.7, lng: -122.4 } },
      { name: "Rider Sees ETA", description: "Location pushed to rider via WebSocket", visuals: [{ kind: "signal", targetId: "RiderApp", color: "green" }] },
    ]},
  ],
});

export const robinhoodExample = defineExample({
  id: "robinhood",
  name: "Robinhood",
  difficulty: "hard",
  description: "Stock trading with order matching, settlement, and real-time portfolio updates.",
  tags: ["trading", "matching-engine", "settlement"],
  patternsUsed: ["order-book", "matching-engine", "event-sourcing"],
  layoutHint: "tiered",
  defaultScenarioId: "rh-trade",
  columns: [
    ["Client"],
    ["APIGateway"],
    ["OrderService", "MatchingEngine", "PortfolioService"],
    ["OrderDB", "TradeLedger", "PriceStream", "SettlementQueue"],
    ["NotificationService"],
  ],
  nodes: [
    { id: "Client", kind: "external", label: "Client" },
    { id: "APIGateway", kind: "gateway", label: "API Gateway" },
    { id: "OrderService", kind: "service", label: "Order Service", icon: "microservice" },
    { id: "MatchingEngine", kind: "service", label: "Matching Engine", icon: "microservice" },
    { id: "PortfolioService", kind: "service", label: "Portfolio Service", icon: "microservice" },
    { id: "OrderDB", kind: "database", label: "Order DB", icon: "postgres" },
    { id: "TradeLedger", kind: "database", label: "Trade Ledger", icon: "postgres" },
    { id: "PriceStream", kind: "queue", label: "Price Stream", icon: "kafka" },
    { id: "SettlementQueue", kind: "queue", label: "Settlement Queue", icon: "kafka" },
    { id: "NotificationService", kind: "service", label: "Notification Service", icon: "microservice" },
  ],
  channels: [
    { id: "ch-order", source: "Client", target: "APIGateway", label: "place order", delivery: "sync", relationship: "command", payloadKind: "command" },
    { id: "ch-submit", source: "APIGateway", target: "OrderService", label: "submit", delivery: "sync", relationship: "command", payloadKind: "command" },
    { source: "OrderService", target: "OrderDB", label: "persist", delivery: "sync", relationship: "command", payloadKind: "command" },
    { id: "ch-match", source: "OrderService", target: "MatchingEngine", label: "match", delivery: "sync", relationship: "command", payloadKind: "command" },
    { id: "ch-ledger", source: "MatchingEngine", target: "TradeLedger", label: "record trade", delivery: "sync", relationship: "command", payloadKind: "command" },
    { id: "ch-settle", source: "MatchingEngine", target: "SettlementQueue", label: "settle", delivery: "async", relationship: "event", payloadKind: "event" },
    { id: "ch-price", source: "MatchingEngine", target: "PriceStream", label: "price update", delivery: "async", relationship: "event", payloadKind: "event" },
    { source: "PriceStream", target: "Client", label: "quote feed", delivery: "async", relationship: "event", payloadKind: "event" },
    { source: "SettlementQueue", target: "PortfolioService", label: "update holdings", delivery: "async", relationship: "event", payloadKind: "event" },
    { id: "ch-notify", source: "MatchingEngine", target: "NotificationService", label: "fill notify", delivery: "async", relationship: "event", payloadKind: "event" },
  ],
  scenarios: [
    { id: "rh-trade", name: "Place Market Order", steps: [
      { name: "Submit Order", channelId: "ch-order", fromNode: "Client", payloadType: "MarketOrder", payloadData: { symbol: "AAPL", qty: 10 } },
      { name: "Route to Engine", channelId: "ch-match", fromNode: "OrderService", payloadType: "MatchOrder", payloadData: { orderId: "o1" } },
      { name: "Record Trade", channelId: "ch-ledger", fromNode: "MatchingEngine", payloadType: "TradeExecuted", payloadData: { price: 175.50 } },
    ]},
    { id: "rh-settle", name: "Settlement", steps: [
      { name: "Enqueue Settlement", channelId: "ch-settle", fromNode: "MatchingEngine", payloadType: "SettlementEvent", payloadData: { tradeId: "t1" } },
      { name: "Update Portfolio", description: "Holdings updated T+1", visuals: [{ kind: "lag", targetId: "PortfolioService", color: "yellow" }] },
    ]},
    { id: "rh-price", name: "Price Feed", steps: [
      { name: "Broadcast Price", channelId: "ch-price", fromNode: "MatchingEngine", payloadType: "PriceUpdate", payloadData: { symbol: "AAPL", price: 175.50 } },
      { name: "Client Update", visuals: [{ kind: "signal", targetId: "Client", color: "green" }] },
    ]},
  ],
});

export const googleDocsExample = defineExample({
  id: "google-docs",
  name: "Google Docs",
  difficulty: "hard",
  description: "Collaborative editing with OT/CRDT, operational transforms, and conflict resolution.",
  tags: ["collaboration", "crdt", "real-time"],
  patternsUsed: ["operational-transform", "websocket-sync", "version-vector"],
  layoutHint: "hub",
  defaultScenarioId: "gd-edit",
  columns: [
    ["ClientA", "ClientB"],
    ["DocGateway"],
    ["CollaborationService", "VersionService"],
    ["DocStore", "OpLog", "PresenceCache"],
  ],
  nodes: [
    { id: "ClientA", kind: "external", label: "Client A" },
    { id: "ClientB", kind: "external", label: "Client B" },
    { id: "DocGateway", kind: "gateway", label: "Doc Gateway" },
    { id: "CollaborationService", kind: "service", label: "Collaboration Service", icon: "microservice" },
    { id: "VersionService", kind: "service", label: "Version Service", icon: "microservice" },
    { id: "DocStore", kind: "database", label: "Doc Store", icon: "postgres" },
    { id: "OpLog", kind: "database", label: "Op Log", icon: "mongodb" },
    { id: "PresenceCache", kind: "database", label: "Presence", icon: "redis" },
  ],
  channels: [
    { id: "ch-edit", source: "ClientA", target: "DocGateway", label: "edit op", delivery: "sync", relationship: "command", payloadKind: "command" },
    { id: "ch-transform", source: "DocGateway", target: "CollaborationService", label: "apply OT", delivery: "sync", relationship: "command", payloadKind: "command" },
    { source: "CollaborationService", target: "OpLog", label: "append op", delivery: "sync", relationship: "command", payloadKind: "command" },
    { id: "ch-version", source: "CollaborationService", target: "VersionService", label: "version check", delivery: "sync", relationship: "query", payloadKind: "query" },
    { source: "VersionService", target: "DocStore", label: "snapshot", delivery: "sync", relationship: "command", payloadKind: "command" },
    { id: "ch-sync", source: "DocGateway", target: "ClientB", label: "broadcast op", delivery: "sync", relationship: "event", payloadKind: "event" },
    { id: "ch-presence", source: "ClientA", target: "DocGateway", label: "cursor update", delivery: "async", relationship: "event", payloadKind: "event" },
    { source: "DocGateway", target: "PresenceCache", label: "store cursor", delivery: "sync", relationship: "command", payloadKind: "command" },
  ],
  scenarios: [
    { id: "gd-edit", name: "Concurrent Edit", steps: [
      { name: "Insert Text", channelId: "ch-edit", fromNode: "ClientA", payloadType: "InsertOp", payloadData: { pos: 5, text: "hello" } },
      { name: "Transform", channelId: "ch-transform", fromNode: "DocGateway", payloadType: "ApplyOT", payloadData: { version: 12 } },
      { name: "Broadcast", channelId: "ch-sync", fromNode: "DocGateway", payloadType: "OpBroadcast", payloadData: { op: "insert" } },
    ]},
    { id: "gd-conflict", name: "Conflict Resolution", steps: [
      { name: "Concurrent Ops", description: "Two clients edit same position", visuals: [{ kind: "highlight", targetId: "CollaborationService", color: "yellow", label: "OT merge" }] },
      { name: "Resolve", channelId: "ch-version", fromNode: "CollaborationService", payloadType: "ResolveConflict", payloadData: {} },
    ]},
    { id: "gd-presence", name: "Cursor Presence", steps: [
      { name: "Move Cursor", channelId: "ch-presence", fromNode: "ClientA", payloadType: "CursorMove", payloadData: { line: 3, col: 10 } },
      { name: "Show to B", visuals: [{ kind: "signal", targetId: "ClientB", color: "green" }] },
    ]},
  ],
});

export const webCrawlerExample = defineExample({
  id: "web-crawler",
  name: "Web Crawler",
  difficulty: "hard",
  description: "Distributed web crawler with URL frontier, politeness, dedup, and content indexing.",
  tags: ["crawler", "distributed", "dedup"],
  patternsUsed: ["url-frontier", "bloom-filter", "politeness-delay"],
  layoutHint: "pipeline",
  defaultScenarioId: "wc-crawl",
  columns: [
    ["SeedURLs"],
    ["CoordinatorService"],
    ["URLFrontier", "BloomFilter", "RobotsCache"],
    ["CrawlerWorker"],
    ["ContentStore", "IndexQueue"],
    ["IndexerService"],
  ],
  nodes: [
    { id: "SeedURLs", kind: "external", label: "Seed URLs" },
    { id: "CoordinatorService", kind: "service", label: "Coordinator", icon: "microservice" },
    { id: "URLFrontier", kind: "queue", label: "URL Frontier", icon: "kafka" },
    { id: "BloomFilter", kind: "database", label: "Visited Bloom Filter", icon: "redis" },
    { id: "CrawlerWorker", kind: "service", label: "Crawler Worker", icon: "microservice" },
    { id: "ContentStore", kind: "database", label: "Content Store", icon: "s3" },
    { id: "IndexQueue", kind: "queue", label: "Index Queue", icon: "kafka" },
    { id: "IndexerService", kind: "service", label: "Indexer", icon: "microservice" },
    { id: "RobotsCache", kind: "database", label: "Robots.txt Cache", icon: "redis" },
  ],
  channels: [
    { id: "ch-seed", source: "SeedURLs", target: "CoordinatorService", label: "seed", delivery: "sync", relationship: "command", payloadKind: "command" },
    { id: "ch-frontier", source: "CoordinatorService", target: "URLFrontier", label: "enqueue", delivery: "async", relationship: "event", payloadKind: "event" },
    { source: "URLFrontier", target: "CrawlerWorker", label: "dequeue", delivery: "async", relationship: "event", payloadKind: "event" },
    { id: "ch-dedup", source: "CrawlerWorker", target: "BloomFilter", label: "check visited", delivery: "sync", relationship: "query", payloadKind: "query" },
    { id: "ch-store", source: "CrawlerWorker", target: "ContentStore", label: "store page", delivery: "sync", relationship: "command", payloadKind: "command" },
    { id: "ch-index", source: "CrawlerWorker", target: "IndexQueue", label: "index page", delivery: "async", relationship: "event", payloadKind: "event" },
    { source: "IndexQueue", target: "IndexerService", label: "build index", delivery: "async", relationship: "event", payloadKind: "event" },
    { source: "CrawlerWorker", target: "RobotsCache", label: "check robots", delivery: "sync", relationship: "query", payloadKind: "query" },
    { source: "CrawlerWorker", target: "URLFrontier", label: "enqueue links", delivery: "async", relationship: "event", payloadKind: "event" },
  ],
  scenarios: [
    { id: "wc-crawl", name: "Crawl Page", steps: [
      { name: "Dequeue URL", description: "Worker picks URL from frontier", visuals: [{ kind: "signal", targetId: "URLFrontier", color: "green" }] },
      { name: "Dedup Check", channelId: "ch-dedup", fromNode: "CrawlerWorker", payloadType: "CheckVisited", payloadData: { url: "https://example.com" } },
      { name: "Store Content", channelId: "ch-store", fromNode: "CrawlerWorker", payloadType: "StorePage", payloadData: { url: "https://example.com" } },
    ]},
    { id: "wc-skip", name: "Skip Duplicate", steps: [
      { name: "Already Visited", channelId: "ch-dedup", fromNode: "CrawlerWorker", visuals: [{ kind: "barrier", targetId: "BloomFilter", color: "yellow", label: "SKIP" }] },
    ]},
    { id: "wc-index", name: "Index Content", steps: [
      { name: "Enqueue Index", channelId: "ch-index", fromNode: "CrawlerWorker", payloadType: "IndexPage", payloadData: { pageId: "p1" } },
      { name: "Build Index", visuals: [{ kind: "signal", targetId: "IndexerService", color: "green" }] },
    ]},
  ],
});

export const adClickAggregatorExample = defineExample({
  id: "ad-click-aggregator",
  name: "Ad Click Aggregator",
  difficulty: "hard",
  description: "High-volume ad click aggregation with stream processing and fraud detection.",
  tags: ["streaming", "aggregation", "fraud"],
  patternsUsed: ["stream-processing", "windowed-aggregation", "fraud-scoring"],
  layoutHint: "pipeline",
  defaultScenarioId: "aca-click",
  columns: [
    ["AdServer"],
    ["ClickGateway"],
    ["ClickStream"],
    ["StreamProcessor", "FraudDetector"],
    ["AggregateStore", "BillingDB"],
    ["DashboardService"],
  ],
  nodes: [
    { id: "AdServer", kind: "external", label: "Ad Server" },
    { id: "ClickGateway", kind: "gateway", label: "Click Gateway" },
    { id: "StreamProcessor", kind: "service", label: "Stream Processor", icon: "microservice" },
    { id: "ClickStream", kind: "queue", label: "Click Stream", icon: "kafka" },
    { id: "AggregateStore", kind: "database", label: "Aggregate Store", icon: "redis" },
    { id: "FraudDetector", kind: "service", label: "Fraud Detector", icon: "microservice" },
    { id: "BillingDB", kind: "database", label: "Billing DB", icon: "postgres" },
    { id: "DashboardService", kind: "service", label: "Dashboard", icon: "microservice" },
  ],
  channels: [
    { id: "ch-click", source: "AdServer", target: "ClickGateway", label: "click event", delivery: "async", relationship: "event", payloadKind: "event" },
    { source: "ClickGateway", target: "ClickStream", label: "publish", delivery: "async", relationship: "event", payloadKind: "event" },
    { id: "ch-process", source: "ClickStream", target: "StreamProcessor", label: "consume", delivery: "async", relationship: "event", payloadKind: "event" },
    { id: "ch-aggregate", source: "StreamProcessor", target: "AggregateStore", label: "window count", delivery: "sync", relationship: "command", payloadKind: "command" },
    { id: "ch-fraud", source: "StreamProcessor", target: "FraudDetector", label: "score", delivery: "sync", relationship: "query", payloadKind: "query" },
    { id: "ch-bill", source: "StreamProcessor", target: "BillingDB", label: "record billing", delivery: "sync", relationship: "command", payloadKind: "command" },
    { source: "DashboardService", target: "AggregateStore", label: "query metrics", delivery: "sync", relationship: "query", payloadKind: "query" },
  ],
  scenarios: [
    { id: "aca-click", name: "Process Click", steps: [
      { name: "Click Event", channelId: "ch-click", fromNode: "AdServer", payloadType: "AdClick", payloadData: { adId: "a1", userId: "u1" } },
      { name: "Stream Process", channelId: "ch-process", fromNode: "ClickStream", payloadType: "ClickEvent", payloadData: {} },
      { name: "Aggregate", channelId: "ch-aggregate", fromNode: "StreamProcessor", payloadType: "WindowCount", payloadData: { window: "1min" } },
    ]},
    { id: "aca-fraud", name: "Fraud Detection", steps: [
      { name: "Score Click", channelId: "ch-fraud", fromNode: "StreamProcessor", payloadType: "FraudScore", payloadData: { score: 0.95 } },
      { name: "Block Fraudulent", visuals: [{ kind: "barrier", targetId: "FraudDetector", color: "red", label: "BLOCKED" }] },
    ]},
    { id: "aca-billing", name: "Billing Record", steps: [
      { name: "Record Charge", channelId: "ch-bill", fromNode: "StreamProcessor", payloadType: "BillingRecord", payloadData: { adId: "a1", cost: 0.50 } },
    ]},
  ],
});

export const fbPostSearchExample = defineExample({
  id: "fb-post-search",
  name: "Facebook Post Search",
  difficulty: "hard",
  description: "Full-text post search with inverted index, typeahead, and privacy filtering.",
  tags: ["search", "inverted-index", "privacy"],
  patternsUsed: ["inverted-index", "typeahead-trie", "acl-filtering"],
  layoutHint: "tiered",
  defaultScenarioId: "fbps-search",
  columns: [
    ["Client"],
    ["SearchGateway"],
    ["SearchService", "IndexService", "PrivacyService"],
    ["InvertedIndex", "TypeaheadTrie", "PostDB", "ACLCache"],
  ],
  nodes: [
    { id: "Client", kind: "external", label: "Client" },
    { id: "SearchGateway", kind: "gateway", label: "Search Gateway" },
    { id: "SearchService", kind: "service", label: "Search Service", icon: "microservice" },
    { id: "IndexService", kind: "service", label: "Index Service", icon: "microservice" },
    { id: "PrivacyService", kind: "service", label: "Privacy Service", icon: "microservice" },
    { id: "InvertedIndex", kind: "database", label: "Inverted Index", icon: "mongodb" },
    { id: "TypeaheadTrie", kind: "database", label: "Typeahead Trie", icon: "redis" },
    { id: "PostDB", kind: "database", label: "Post DB", icon: "postgres" },
    { id: "ACLCache", kind: "database", label: "ACL Cache", icon: "redis" },
  ],
  channels: [
    { id: "ch-search", source: "Client", target: "SearchGateway", label: "search", delivery: "sync", relationship: "query", payloadKind: "query" },
    { id: "ch-query", source: "SearchGateway", target: "SearchService", label: "full-text", delivery: "sync", relationship: "query", payloadKind: "query" },
    { id: "ch-index", source: "SearchService", target: "InvertedIndex", label: "lookup", delivery: "sync", relationship: "query", payloadKind: "query" },
    { id: "ch-privacy", source: "SearchService", target: "PrivacyService", label: "filter ACL", delivery: "sync", relationship: "query", payloadKind: "query" },
    { source: "PrivacyService", target: "ACLCache", label: "check access", delivery: "sync", relationship: "query", payloadKind: "query" },
    { id: "ch-typeahead", source: "Client", target: "SearchGateway", label: "autocomplete", delivery: "sync", relationship: "query", payloadKind: "query" },
    { source: "SearchGateway", target: "SearchService", label: "prefix", delivery: "sync", relationship: "query", payloadKind: "query" },
    { source: "SearchService", target: "TypeaheadTrie", label: "prefix match", delivery: "sync", relationship: "query", payloadKind: "query" },
    { source: "PostDB", target: "IndexService", label: "CDC", delivery: "async", relationship: "event", payloadKind: "event" },
    { source: "IndexService", target: "InvertedIndex", label: "index post", delivery: "sync", relationship: "command", payloadKind: "command" },
    { source: "IndexService", target: "PostDB", label: "read post", delivery: "sync", relationship: "query", payloadKind: "query" },
  ],
  scenarios: [
    { id: "fbps-search", name: "Search Posts", steps: [
      { name: "Query", channelId: "ch-search", fromNode: "Client", payloadType: "SearchQuery", payloadData: { q: "birthday party" } },
      { name: "Index Lookup", channelId: "ch-index", fromNode: "SearchService", payloadType: "IndexSearch", payloadData: { terms: ["birthday", "party"] } },
      { name: "Privacy Filter", channelId: "ch-privacy", fromNode: "SearchService", payloadType: "FilterACL", payloadData: { userId: "u1" } },
    ]},
    { id: "fbps-typeahead", name: "Typeahead", steps: [
      { name: "Prefix Query", channelId: "ch-typeahead", fromNode: "Client", payloadType: "Typeahead", payloadData: { prefix: "birth" } },
      { name: "Trie Match", description: "Return top suggestions from trie", visuals: [{ kind: "signal", targetId: "TypeaheadTrie", color: "green" }] },
    ]},
    { id: "fbps-index", name: "Index New Post", steps: [
      { name: "Tokenize", description: "Index service tokenizes and indexes post", visuals: [{ kind: "highlight", targetId: "IndexService", color: "yellow" }] },
      { name: "Update Index", visuals: [{ kind: "signal", targetId: "InvertedIndex", color: "green" }] },
    ]},
  ],
});

export const paymentSystemExample = defineExample({
  id: "payment-system",
  name: "Payment System",
  difficulty: "hard",
  description: "Payment processing with idempotency, ledger, double-entry accounting, and reconciliation.",
  tags: ["payments", "ledger", "idempotency"],
  patternsUsed: ["double-entry-ledger", "idempotency-key", "saga-pattern"],
  layoutHint: "pipeline",
  defaultScenarioId: "pay-charge",
  columns: [
    ["Client"],
    ["PaymentGateway"],
    ["PaymentService"],
    ["IdempotencyCache", "LedgerDB", "SettlementQueue"],
    ["BankConnector", "ReconciliationService"],
  ],
  nodes: [
    { id: "Client", kind: "external", label: "Client" },
    { id: "PaymentGateway", kind: "gateway", label: "Payment Gateway" },
    { id: "PaymentService", kind: "service", label: "Payment Service", icon: "microservice" },
    { id: "LedgerDB", kind: "database", label: "Ledger DB", icon: "postgres" },
    { id: "IdempotencyCache", kind: "database", label: "Idempotency Keys", icon: "redis" },
    { id: "SettlementQueue", kind: "queue", label: "Settlement Queue", icon: "kafka" },
    { id: "BankConnector", kind: "external", label: "Bank Connector" },
    { id: "ReconciliationService", kind: "service", label: "Reconciliation", icon: "microservice" },
  ],
  channels: [
    { id: "ch-pay", source: "Client", target: "PaymentGateway", label: "charge", delivery: "sync", relationship: "command", payloadKind: "command" },
    { id: "ch-process", source: "PaymentGateway", target: "PaymentService", label: "process", delivery: "sync", relationship: "command", payloadKind: "command" },
    { id: "ch-idem", source: "PaymentService", target: "IdempotencyCache", label: "check key", delivery: "sync", relationship: "query", payloadKind: "query" },
    { id: "ch-ledger", source: "PaymentService", target: "LedgerDB", label: "double-entry", delivery: "sync", relationship: "command", payloadKind: "command" },
    { id: "ch-settle", source: "PaymentService", target: "SettlementQueue", label: "settle", delivery: "async", relationship: "event", payloadKind: "event" },
    { source: "SettlementQueue", target: "BankConnector", label: "bank transfer", delivery: "async", relationship: "event", payloadKind: "event" },
    { source: "SettlementQueue", target: "ReconciliationService", label: "reconcile", delivery: "async", relationship: "event", payloadKind: "event" },
  ],
  scenarios: [
    { id: "pay-charge", name: "Process Payment", steps: [
      { name: "Charge Request", channelId: "ch-pay", fromNode: "Client", payloadType: "Charge", payloadData: { amount: 99.99, idempotencyKey: "k1" } },
      { name: "Idempotency Check", channelId: "ch-idem", fromNode: "PaymentService", payloadType: "CheckKey", payloadData: { key: "k1" } },
      { name: "Record Ledger", channelId: "ch-ledger", fromNode: "PaymentService", payloadType: "DoubleEntry", payloadData: { debit: "user", credit: "merchant" } },
    ]},
    { id: "pay-duplicate", name: "Duplicate Request", steps: [
      { name: "Retry", channelId: "ch-pay", fromNode: "Client", payloadType: "Charge", payloadData: { idempotencyKey: "k1" } },
      { name: "Return Cached", channelId: "ch-idem", fromNode: "PaymentService", visuals: [{ kind: "signal", targetId: "IdempotencyCache", color: "green", label: "CACHED" }] },
    ]},
    { id: "pay-settle", name: "Settlement", steps: [
      { name: "Enqueue", channelId: "ch-settle", fromNode: "PaymentService", payloadType: "SettlementJob", payloadData: { paymentId: "p1" } },
      { name: "Bank Transfer", visuals: [{ kind: "signal", targetId: "BankConnector", color: "green" }] },
    ]},
  ],
});

export const metricsMonitoringExample = defineExample({
  id: "metrics-monitoring",
  name: "Metrics Monitoring",
  difficulty: "hard",
  description: "Time-series metrics ingestion, aggregation, alerting, and dashboard queries.",
  tags: ["monitoring", "time-series", "alerting"],
  patternsUsed: ["time-series-db", "downsampling", "alert-evaluation"],
  layoutHint: "tiered",
  defaultScenarioId: "mm-ingest",
  columns: [
    ["AppServers"],
    ["MetricsAgent"],
    ["IngestGateway"],
    ["AggregationService"],
    ["TimeSeriesDB", "AlertQueue"],
    ["DownsampleWorker", "AlertService", "DashboardService"],
  ],
  nodes: [
    { id: "AppServers", kind: "external", label: "App Servers" },
    { id: "MetricsAgent", kind: "service", label: "Metrics Agent", icon: "microservice" },
    { id: "IngestGateway", kind: "gateway", label: "Ingest Gateway" },
    { id: "AggregationService", kind: "service", label: "Aggregation Service", icon: "microservice" },
    { id: "TimeSeriesDB", kind: "database", label: "Time Series DB", icon: "mongodb" },
    { id: "AlertQueue", kind: "queue", label: "Alert Queue", icon: "kafka" },
    { id: "DownsampleWorker", kind: "service", label: "Downsample Worker", icon: "microservice" },
    { id: "AlertService", kind: "service", label: "Alert Service", icon: "microservice" },
    { id: "DashboardService", kind: "service", label: "Dashboard Service", icon: "microservice" },
  ],
  channels: [
    { id: "ch-emit", source: "AppServers", target: "MetricsAgent", label: "emit metric", delivery: "async", relationship: "event", payloadKind: "event" },
    { id: "ch-ingest", source: "MetricsAgent", target: "IngestGateway", label: "batch push", delivery: "async", relationship: "event", payloadKind: "event" },
    { source: "IngestGateway", target: "AggregationService", label: "aggregate", delivery: "sync", relationship: "command", payloadKind: "command" },
    { id: "ch-store", source: "AggregationService", target: "TimeSeriesDB", label: "write points", delivery: "sync", relationship: "command", payloadKind: "command" },
    { id: "ch-alert", source: "AggregationService", target: "AlertQueue", label: "threshold breach", delivery: "async", relationship: "event", payloadKind: "event" },
    { source: "AlertQueue", target: "AlertService", label: "evaluate", delivery: "async", relationship: "event", payloadKind: "event" },
    { source: "AggregationService", target: "DownsampleWorker", label: "schedule rollup", delivery: "async", relationship: "event", payloadKind: "event" },
    { id: "ch-query", source: "DashboardService", target: "TimeSeriesDB", label: "query range", delivery: "sync", relationship: "query", payloadKind: "query" },
    { source: "DownsampleWorker", target: "TimeSeriesDB", label: "rollup", delivery: "sync", relationship: "command", payloadKind: "command" },
  ],
  scenarios: [
    { id: "mm-ingest", name: "Ingest Metrics", steps: [
      { name: "Emit", channelId: "ch-emit", fromNode: "AppServers", payloadType: "MetricPoint", payloadData: { name: "cpu.usage", value: 85 } },
      { name: "Batch Ingest", channelId: "ch-ingest", fromNode: "MetricsAgent", payloadType: "MetricBatch", payloadData: { count: 1000 } },
      { name: "Store", channelId: "ch-store", fromNode: "AggregationService", payloadType: "WritePoints", payloadData: {} },
    ]},
    { id: "mm-alert", name: "Fire Alert", steps: [
      { name: "Threshold Breach", channelId: "ch-alert", fromNode: "AggregationService", payloadType: "AlertTrigger", payloadData: { metric: "cpu.usage", threshold: 90 } },
      { name: "Notify On-call", visuals: [{ kind: "signal", targetId: "AlertService", color: "red" }] },
    ]},
    { id: "mm-dashboard", name: "Dashboard Query", steps: [
      { name: "Query Range", channelId: "ch-query", fromNode: "DashboardService", payloadType: "RangeQuery", payloadData: { from: "1h", to: "now" } },
      { name: "Render Chart", visuals: [{ kind: "signal", targetId: "DashboardService", color: "green" }] },
    ]},
  ],
});

export const onlineChessExample = defineExample({
  id: "online-chess",
  name: "Online Chess",
  difficulty: "hard",
  description: "Real-time chess with move validation, game state, matchmaking, and spectator support.",
  tags: ["gaming", "state-machine", "real-time"],
  patternsUsed: ["game-state-machine", "move-validation", "elo-matchmaking"],
  layoutHint: "hub",
  defaultScenarioId: "chess-move",
  columns: [
    ["PlayerWhite", "PlayerBlack", "SpectatorApp"],
    ["GameGateway"],
    ["GameService", "MatchmakingService"],
    ["GameStateDB", "MoveLog", "RatingCache"],
  ],
  nodes: [
    { id: "PlayerWhite", kind: "external", label: "Player White" },
    { id: "PlayerBlack", kind: "external", label: "Player Black" },
    { id: "SpectatorApp", kind: "external", label: "Spectator App" },
    { id: "GameGateway", kind: "gateway", label: "Game Gateway" },
    { id: "GameService", kind: "service", label: "Game Service", icon: "microservice" },
    { id: "MatchmakingService", kind: "service", label: "Matchmaking", icon: "microservice" },
    { id: "GameStateDB", kind: "database", label: "Game State", icon: "redis" },
    { id: "MoveLog", kind: "database", label: "Move Log", icon: "postgres" },
    { id: "RatingCache", kind: "database", label: "ELO Ratings", icon: "redis" },
  ],
  channels: [
    { id: "ch-move", source: "PlayerWhite", target: "GameGateway", label: "make move", delivery: "sync", relationship: "command", payloadKind: "command" },
    { id: "ch-validate", source: "GameGateway", target: "GameService", label: "validate", delivery: "sync", relationship: "command", payloadKind: "command" },
    { source: "GameService", target: "GameStateDB", label: "update state", delivery: "sync", relationship: "command", payloadKind: "command" },
    { id: "ch-log", source: "GameService", target: "MoveLog", label: "append move", delivery: "sync", relationship: "command", payloadKind: "command" },
    { id: "ch-broadcast", source: "GameGateway", target: "PlayerBlack", label: "sync move", delivery: "sync", relationship: "event", payloadKind: "event" },
    { id: "ch-spectate", source: "GameGateway", target: "SpectatorApp", label: "broadcast", delivery: "sync", relationship: "event", payloadKind: "event" },
    { id: "ch-match", source: "PlayerWhite", target: "MatchmakingService", label: "find opponent", delivery: "sync", relationship: "command", payloadKind: "command" },
    { source: "MatchmakingService", target: "RatingCache", label: "elo lookup", delivery: "sync", relationship: "query", payloadKind: "query" },
  ],
  scenarios: [
    { id: "chess-move", name: "Make Move", steps: [
      { name: "Play e4", channelId: "ch-move", fromNode: "PlayerWhite", payloadType: "Move", payloadData: { from: "e2", to: "e4" } },
      { name: "Validate", channelId: "ch-validate", fromNode: "GameGateway", payloadType: "ValidateMove", payloadData: { legal: true } },
      { name: "Sync to Black", channelId: "ch-broadcast", fromNode: "GameGateway", payloadType: "MoveSync", payloadData: { from: "e2", to: "e4" } },
    ]},
    { id: "chess-invalid", name: "Invalid Move", steps: [
      { name: "Illegal Move", channelId: "ch-move", fromNode: "PlayerWhite", payloadType: "Move", payloadData: { from: "e2", to: "e5" } },
      { name: "Rejected", channelId: "ch-validate", fromNode: "GameGateway", visuals: [{ kind: "barrier", targetId: "GameService", color: "red", label: "INVALID" }] },
    ]},
    { id: "chess-match", name: "Matchmaking", steps: [
      { name: "Queue", channelId: "ch-match", fromNode: "PlayerWhite", payloadType: "FindMatch", payloadData: { rating: 1500 } },
      { name: "ELO Match", visuals: [{ kind: "signal", targetId: "RatingCache", color: "green", label: "Matched 1495" }] },
    ]},
  ],
});

export const chatgptExample = defineExample({
  id: "chatgpt",
  name: "ChatGPT",
  difficulty: "hard",
  description: "LLM chat with prompt routing, token streaming, context management, and rate limiting.",
  tags: ["llm", "streaming", "inference"],
  patternsUsed: ["prompt-routing", "token-streaming", "context-window"],
  layoutHint: "pipeline",
  defaultScenarioId: "gpt-chat",
  columns: [
    ["Client"],
    ["ChatGateway"],
    ["OrchestratorService"],
    ["ContextStore", "RateLimiter", "ModelRouter"],
    ["InferenceCluster"],
    ["TokenStream", "ConversationDB"],
  ],
  nodes: [
    { id: "Client", kind: "external", label: "Client" },
    { id: "ChatGateway", kind: "gateway", label: "Chat Gateway" },
    { id: "OrchestratorService", kind: "service", label: "Orchestrator", icon: "microservice" },
    { id: "ContextStore", kind: "database", label: "Context Store", icon: "redis" },
    { id: "ModelRouter", kind: "service", label: "Model Router", icon: "microservice" },
    { id: "RateLimiter", kind: "database", label: "Rate Limiter", icon: "redis" },
    { id: "InferenceCluster", kind: "service", label: "Inference Cluster", icon: "microservice" },
    { id: "ConversationDB", kind: "database", label: "Conversation DB", icon: "postgres" },
    { id: "TokenStream", kind: "queue", label: "Token Stream", icon: "kafka" },
  ],
  channels: [
    { id: "ch-prompt", source: "Client", target: "ChatGateway", label: "send prompt", delivery: "sync", relationship: "command", payloadKind: "command" },
    { id: "ch-orchestrate", source: "ChatGateway", target: "OrchestratorService", label: "process", delivery: "sync", relationship: "command", payloadKind: "command" },
    { id: "ch-context", source: "OrchestratorService", target: "ContextStore", label: "load context", delivery: "sync", relationship: "query", payloadKind: "query" },
    { id: "ch-rate", source: "OrchestratorService", target: "RateLimiter", label: "check quota", delivery: "sync", relationship: "query", payloadKind: "query" },
    { id: "ch-route", source: "OrchestratorService", target: "ModelRouter", label: "route model", delivery: "sync", relationship: "command", payloadKind: "command" },
    { source: "ModelRouter", target: "InferenceCluster", label: "inference", delivery: "sync", relationship: "command", payloadKind: "command" },
    { id: "ch-stream", source: "InferenceCluster", target: "TokenStream", label: "token stream", delivery: "async", relationship: "event", payloadKind: "event" },
    { source: "TokenStream", target: "ChatGateway", label: "SSE push", delivery: "async", relationship: "event", payloadKind: "event" },
    { source: "ChatGateway", target: "Client", label: "stream tokens", delivery: "sync", relationship: "event", payloadKind: "event" },
    { source: "OrchestratorService", target: "ConversationDB", label: "persist", delivery: "sync", relationship: "command", payloadKind: "command" },
  ],
  scenarios: [
    { id: "gpt-chat", name: "Chat Completion", steps: [
      { name: "Send Prompt", channelId: "ch-prompt", fromNode: "Client", payloadType: "ChatPrompt", payloadData: { message: "Explain OT" } },
      { name: "Load Context", channelId: "ch-context", fromNode: "OrchestratorService", payloadType: "LoadContext", payloadData: { conversationId: "c1" } },
      { name: "Route to Model", channelId: "ch-route", fromNode: "OrchestratorService", payloadType: "SelectModel", payloadData: { model: "gpt-4" } },
    ]},
    { id: "gpt-stream", name: "Stream Tokens", steps: [
      { name: "Inference", description: "Model generates tokens", visuals: [{ kind: "highlight", targetId: "InferenceCluster", color: "yellow" }] },
      { name: "Stream SSE", channelId: "ch-stream", fromNode: "InferenceCluster", payloadType: "TokenChunk", payloadData: { token: "Operational" } },
      { name: "Client Receives", visuals: [{ kind: "signal", targetId: "Client", color: "green" }] },
    ]},
    { id: "gpt-rate-limit", name: "Rate Limited", steps: [
      { name: "Check Quota", channelId: "ch-rate", fromNode: "OrchestratorService", payloadType: "CheckQuota", payloadData: { userId: "u1" } },
      { name: "Quota Exceeded", visuals: [{ kind: "barrier", targetId: "RateLimiter", color: "red", label: "429" }] },
    ]},
  ],
});

export const hardExamples = [
  youtubeTopKExample,
  uberExample,
  robinhoodExample,
  googleDocsExample,
  webCrawlerExample,
  adClickAggregatorExample,
  fbPostSearchExample,
  paymentSystemExample,
  metricsMonitoringExample,
  onlineChessExample,
  chatgptExample,
];
