import { defineExample } from "./define-example.js";

export const ticketmasterExample = defineExample({
  id: "ticketmaster",
  name: "Ticketmaster",
  difficulty: "medium",
  description: "High-demand ticket sales with inventory locking, queueing, and idempotent checkout.",
  tags: ["inventory", "concurrency", "queue"],
  patternsUsed: ["distributed-lock", "virtual-waiting-room", "idempotency"],
  layoutHint: "pipeline",
  defaultScenarioId: "tm-purchase",
  columns: [
    ["Client"],
    ["CDN"],
    ["APIGateway"],
    ["BookingService"],
    ["RedisLock", "InventoryDB", "PaymentQueue"],
    ["PaymentService"],
  ],
  nodes: [
    { id: "Client", kind: "external", label: "Client" },
    { id: "CDN", kind: "gateway", label: "CDN", icon: "cdn" },
    { id: "APIGateway", kind: "gateway", label: "API Gateway" },
    { id: "BookingService", kind: "service", label: "Booking Service", icon: "microservice" },
    { id: "RedisLock", kind: "database", label: "Seat Locks", icon: "redis" },
    { id: "InventoryDB", kind: "database", label: "Inventory DB", icon: "postgres" },
    { id: "PaymentQueue", kind: "queue", label: "Payment Queue", icon: "kafka" },
    { id: "PaymentService", kind: "service", label: "Payment Service", icon: "microservice" },
  ],
  channels: [
    { source: "Client", target: "CDN", label: "browse", delivery: "sync", relationship: "query", payloadKind: "request" },
    { source: "CDN", target: "APIGateway", label: "forward", delivery: "sync", relationship: "command", payloadKind: "request" },
    { id: "ch-book", source: "APIGateway", target: "BookingService", label: "reserve seat", delivery: "sync", relationship: "command", payloadKind: "command" },
    { id: "ch-lock", source: "BookingService", target: "RedisLock", label: "acquire lock", delivery: "sync", relationship: "command", payloadKind: "command" },
    { id: "ch-inv", source: "BookingService", target: "InventoryDB", label: "decrement", delivery: "sync", relationship: "command", payloadKind: "command" },
    { id: "ch-pay", source: "BookingService", target: "PaymentQueue", label: "checkout", delivery: "async", relationship: "event", payloadKind: "event" },
    { source: "PaymentQueue", target: "PaymentService", label: "process", delivery: "async", relationship: "event", payloadKind: "event" },
  ],
  scenarios: [
    { id: "tm-purchase", name: "Purchase Ticket", steps: [
      { name: "Reserve Seat", channelId: "ch-book", fromNode: "APIGateway", payloadType: "ReserveSeat", payloadData: { seatId: "A12" } },
      { name: "Acquire Lock", channelId: "ch-lock", fromNode: "BookingService", payloadType: "LockSeat", payloadData: { ttl: 300 } },
      { name: "Confirm Inventory", channelId: "ch-inv", fromNode: "BookingService", payloadType: "DecrementInventory", payloadData: { eventId: "e1" } },
    ]},
    { id: "tm-sold-out", name: "Sold Out", steps: [
      { name: "Reserve Attempt", channelId: "ch-book", fromNode: "APIGateway", payloadType: "ReserveSeat", payloadData: { seatId: "A12" } },
      { name: "Lock Failed", channelId: "ch-lock", fromNode: "BookingService", visuals: [{ kind: "barrier", targetId: "RedisLock", color: "red", label: "SOLD OUT" }] },
    ]},
    { id: "tm-payment", name: "Async Payment", steps: [
      { name: "Enqueue Payment", channelId: "ch-pay", fromNode: "BookingService", payloadType: "CheckoutEvent", payloadData: { orderId: "o1" } },
      { name: "Process Payment", description: "Payment service charges card and confirms booking", visuals: [{ kind: "signal", targetId: "PaymentService", color: "green" }] },
    ]},
  ],
});

export const instagramExample = defineExample({
  id: "instagram",
  name: "Instagram",
  difficulty: "medium",
  description: "Photo sharing with blob storage, fan-out feed generation, and CDN delivery.",
  tags: ["social", "fan-out", "blob-storage"],
  patternsUsed: ["write-behind-feed", "blob-storage", "cdn-caching"],
  layoutHint: "tiered",
  defaultScenarioId: "ig-post",
  columns: [
    ["Client"],
    ["APIGateway"],
    ["PostService", "FeedService", "MediaService"],
    ["PostDB", "FeedCache", "ObjectStore"],
    ["CDN"],
  ],
  nodes: [
    { id: "Client", kind: "external", label: "Client" },
    { id: "APIGateway", kind: "gateway", label: "API Gateway" },
    { id: "PostService", kind: "service", label: "Post Service", icon: "microservice" },
    { id: "FeedService", kind: "service", label: "Feed Service", icon: "microservice" },
    { id: "MediaService", kind: "service", label: "Media Service", icon: "microservice" },
    { id: "PostDB", kind: "database", label: "Post DB", icon: "postgres" },
    { id: "FeedCache", kind: "database", label: "Feed Cache", icon: "redis" },
    { id: "ObjectStore", kind: "database", label: "Object Store", icon: "s3" },
    { id: "CDN", kind: "gateway", label: "CDN", icon: "cdn" },
  ],
  channels: [
    { id: "ch-upload", source: "Client", target: "APIGateway", label: "upload photo", delivery: "sync", relationship: "command", payloadKind: "command" },
    { id: "ch-media", source: "APIGateway", target: "MediaService", label: "store blob", delivery: "sync", relationship: "command", payloadKind: "command" },
    { source: "MediaService", target: "ObjectStore", label: "put object", delivery: "sync", relationship: "command", payloadKind: "command" },
    { source: "Client", target: "ObjectStore", label: "PUT photo", delivery: "sync", relationship: "command", payloadKind: "command" },
    { id: "ch-post", source: "APIGateway", target: "PostService", label: "create post", delivery: "sync", relationship: "command", payloadKind: "command" },
    { source: "PostService", target: "PostDB", label: "persist", delivery: "sync", relationship: "command", payloadKind: "command" },
    { id: "ch-fanout", source: "PostService", target: "FeedService", label: "fan-out", delivery: "async", relationship: "event", payloadKind: "event" },
    { id: "ch-feed", source: "FeedService", target: "FeedCache", label: "push feed", delivery: "sync", relationship: "command", payloadKind: "command" },
    { source: "APIGateway", target: "FeedService", label: "read feed", delivery: "sync", relationship: "query", payloadKind: "query" },
    { source: "Client", target: "CDN", label: "fetch media", delivery: "sync", relationship: "query", payloadKind: "query" },
    { id: "ch-cdn", source: "CDN", target: "ObjectStore", label: "origin fetch", delivery: "sync", relationship: "query", payloadKind: "query" },
  ],
  scenarios: [
    { id: "ig-post", name: "Create Post", steps: [
      { name: "Upload Photo", channelId: "ch-upload", fromNode: "Client", payloadType: "UploadPhoto", payloadData: { size: "2MB" } },
      { name: "Store Blob", channelId: "ch-media", fromNode: "APIGateway", payloadType: "PutObject", payloadData: { key: "p1.jpg" } },
      { name: "Create Post", channelId: "ch-post", fromNode: "APIGateway", payloadType: "CreatePost", payloadData: { caption: "sunset" } },
    ]},
    { id: "ig-feed", name: "Read Feed", steps: [
      { name: "Fan-out", channelId: "ch-fanout", fromNode: "PostService", payloadType: "NewPostEvent", payloadData: { postId: "p1" } },
      { name: "Update Feeds", channelId: "ch-feed", fromNode: "FeedService", payloadType: "PushToFollowers", payloadData: { followers: 500 } },
    ]},
    { id: "ig-cdn", name: "Serve Image", steps: [
      { name: "CDN Request", channelId: "ch-cdn", fromNode: "CDN", payloadType: "GetObject", payloadData: { key: "p1.jpg" } },
      { name: "Cache Hit", visuals: [{ kind: "signal", targetId: "CDN", color: "green", label: "HIT" }] },
    ]},
  ],
});

export const fbNewsFeedExample = defineExample({
  id: "fb-news-feed",
  name: "Facebook News Feed",
  difficulty: "medium",
  description: "Hybrid push/pull feed with celebrity fan-out and timeline ranking.",
  tags: ["social", "fan-out", "ranking"],
  patternsUsed: ["hybrid-fanout", "feed-ranking", "timeline-cache"],
  layoutHint: "hub",
  defaultScenarioId: "fb-pull-feed",
  columns: [
    ["Client"],
    ["FeedGateway"],
    ["FeedService", "RankingService", "PostService"],
    ["FeedCache", "PostDB", "EventQueue"],
  ],
  nodes: [
    { id: "Client", kind: "external", label: "Client" },
    { id: "FeedGateway", kind: "gateway", label: "Feed Gateway" },
    { id: "FeedService", kind: "service", label: "Feed Service", icon: "microservice" },
    { id: "RankingService", kind: "service", label: "Ranking Service", icon: "microservice" },
    { id: "PostService", kind: "service", label: "Post Service", icon: "microservice" },
    { id: "FeedCache", kind: "database", label: "Feed Cache", icon: "redis" },
    { id: "PostDB", kind: "database", label: "Post DB", icon: "postgres" },
    { id: "EventQueue", kind: "queue", label: "Event Queue", icon: "kafka" },
  ],
  channels: [
    { id: "ch-read", source: "Client", target: "FeedGateway", label: "get feed", delivery: "sync", relationship: "query", payloadKind: "query" },
    { id: "ch-feed", source: "FeedGateway", target: "FeedService", label: "assemble", delivery: "sync", relationship: "query", payloadKind: "query" },
    { id: "ch-cache", source: "FeedService", target: "FeedCache", label: "read cache", delivery: "sync", relationship: "query", payloadKind: "query" },
    { id: "ch-rank", source: "FeedService", target: "RankingService", label: "rank", delivery: "sync", relationship: "query", payloadKind: "query" },
    { id: "ch-write", source: "Client", target: "FeedGateway", label: "new post", delivery: "sync", relationship: "command", payloadKind: "command" },
    { source: "FeedGateway", target: "PostService", label: "create post", delivery: "sync", relationship: "command", payloadKind: "command" },
    { source: "PostService", target: "PostDB", label: "persist", delivery: "sync", relationship: "command", payloadKind: "command" },
    { id: "ch-fanout", source: "PostService", target: "EventQueue", label: "fan-out event", delivery: "async", relationship: "event", payloadKind: "event" },
    { source: "EventQueue", target: "FeedService", label: "precompute feed", delivery: "async", relationship: "event", payloadKind: "event" },
    { source: "FeedService", target: "FeedCache", label: "write timeline", delivery: "sync", relationship: "command", payloadKind: "command" },
    { source: "FeedService", target: "PostDB", label: "hydrate posts", delivery: "sync", relationship: "query", payloadKind: "query" },
  ],
  scenarios: [
    { id: "fb-pull-feed", name: "Pull Feed", steps: [
      { name: "Request Feed", channelId: "ch-read", fromNode: "Client", payloadType: "GetFeed", payloadData: { userId: "u1" } },
      { name: "Cache Lookup", channelId: "ch-cache", fromNode: "FeedService", payloadType: "GetCachedFeed", payloadData: { userId: "u1" } },
      { name: "Rank Posts", channelId: "ch-rank", fromNode: "FeedService", payloadType: "RankFeed", payloadData: { limit: 20 } },
    ]},
    { id: "fb-celebrity", name: "Celebrity Post", steps: [
      { name: "Create Post", channelId: "ch-write", fromNode: "Client", payloadType: "CreatePost", payloadData: { text: "hello" } },
      { name: "Skip Fan-out", description: "Celebrity posts use pull model on read", visuals: [{ kind: "lag", targetId: "EventQueue", color: "yellow", label: "Pull only" }] },
    ]},
    { id: "fb-fanout", name: "Regular User Fan-out", steps: [
      { name: "Persist Post", channelId: "ch-write", fromNode: "Client", payloadType: "CreatePost", payloadData: { userId: "u2" } },
      { name: "Push to Followers", channelId: "ch-fanout", fromNode: "PostService", payloadType: "FanOutEvent", payloadData: { followers: 200 } },
    ]},
  ],
});

export const tinderExample = defineExample({
  id: "tinder",
  name: "Tinder",
  difficulty: "medium",
  description: "Geo-based match discovery with swipe actions and mutual match notifications.",
  tags: ["geo", "matching", "real-time"],
  patternsUsed: ["geo-index", "mutual-match", "event-notification"],
  layoutHint: "pipeline",
  defaultScenarioId: "tinder-swipe",
  columns: [
    ["Client"],
    ["APIGateway"],
    ["DiscoveryService"],
    ["GeoIndex", "SwipeDB", "MatchQueue"],
    ["NotificationService"],
  ],
  nodes: [
    { id: "Client", kind: "external", label: "Client" },
    { id: "APIGateway", kind: "gateway", label: "API Gateway" },
    { id: "DiscoveryService", kind: "service", label: "Discovery Service", icon: "microservice" },
    { id: "GeoIndex", kind: "database", label: "Geo Index", icon: "mongodb" },
    { id: "SwipeDB", kind: "database", label: "Swipe DB", icon: "postgres" },
    { id: "MatchQueue", kind: "queue", label: "Match Queue", icon: "kafka" },
    { id: "NotificationService", kind: "service", label: "Notification Service", icon: "microservice" },
  ],
  channels: [
    { id: "ch-discover", source: "Client", target: "APIGateway", label: "discover", delivery: "sync", relationship: "query", payloadKind: "query" },
    { source: "APIGateway", target: "DiscoveryService", label: "nearby", delivery: "sync", relationship: "query", payloadKind: "query" },
    { id: "ch-geo", source: "DiscoveryService", target: "GeoIndex", label: "geo query", delivery: "sync", relationship: "query", payloadKind: "query" },
    { id: "ch-swipe", source: "Client", target: "APIGateway", label: "swipe", delivery: "sync", relationship: "command", payloadKind: "command" },
    { source: "APIGateway", target: "DiscoveryService", label: "record action", delivery: "sync", relationship: "command", payloadKind: "command" },
    { id: "ch-store", source: "DiscoveryService", target: "SwipeDB", label: "record swipe", delivery: "sync", relationship: "command", payloadKind: "command" },
    { id: "ch-match", source: "DiscoveryService", target: "MatchQueue", label: "check match", delivery: "async", relationship: "event", payloadKind: "event" },
    { source: "MatchQueue", target: "NotificationService", label: "notify", delivery: "async", relationship: "event", payloadKind: "event" },
  ],
  scenarios: [
    { id: "tinder-swipe", name: "Swipe Right", steps: [
      { name: "Swipe", channelId: "ch-swipe", fromNode: "Client", payloadType: "SwipeRight", payloadData: { targetId: "u2" } },
      { name: "Record Swipe", channelId: "ch-store", fromNode: "DiscoveryService", payloadType: "StoreSwipe", payloadData: { direction: "right" } },
      { name: "Check Mutual", channelId: "ch-match", fromNode: "DiscoveryService", payloadType: "CheckMatch", payloadData: { userId: "u2" } },
    ]},
    { id: "tinder-discover", name: "Discover Nearby", steps: [
      { name: "Request Cards", channelId: "ch-discover", fromNode: "Client", payloadType: "GetCards", payloadData: { lat: 37.7, lng: -122.4 } },
      { name: "Geo Filter", channelId: "ch-geo", fromNode: "DiscoveryService", payloadType: "NearbyUsers", payloadData: { radius: "50km" } },
    ]},
    { id: "tinder-match", name: "Mutual Match", steps: [
      { name: "Match Found", channelId: "ch-match", fromNode: "DiscoveryService", payloadType: "MatchEvent", payloadData: { matchId: "m1" } },
      { name: "Push Notification", visuals: [{ kind: "signal", targetId: "NotificationService", color: "green", label: "It's a match!" }] },
    ]},
  ],
});

export const leetcodeExample = defineExample({
  id: "leetcode",
  name: "LeetCode",
  difficulty: "medium",
  description: "Online judge with code submission queue, sandboxed execution, and result storage.",
  tags: ["queue", "sandbox", "async-processing"],
  patternsUsed: ["job-queue", "worker-pool", "result-polling"],
  layoutHint: "pipeline",
  defaultScenarioId: "lc-submit",
  columns: [
    ["Client"],
    ["APIGateway"],
    ["SubmissionService"],
    ["SubmissionDB", "JudgeQueue"],
    ["JudgeWorker", "ResultCache"],
  ],
  nodes: [
    { id: "Client", kind: "external", label: "Client" },
    { id: "APIGateway", kind: "gateway", label: "API Gateway" },
    { id: "SubmissionService", kind: "service", label: "Submission Service", icon: "microservice" },
    { id: "SubmissionDB", kind: "database", label: "Submission DB", icon: "postgres" },
    { id: "JudgeQueue", kind: "queue", label: "Judge Queue", icon: "kafka" },
    { id: "JudgeWorker", kind: "service", label: "Judge Worker", icon: "microservice" },
    { id: "ResultCache", kind: "database", label: "Result Cache", icon: "redis" },
  ],
  channels: [
    { id: "ch-submit", source: "Client", target: "APIGateway", label: "submit code", delivery: "sync", relationship: "command", payloadKind: "command" },
    { id: "ch-persist", source: "APIGateway", target: "SubmissionService", label: "enqueue", delivery: "sync", relationship: "command", payloadKind: "command" },
    { source: "SubmissionService", target: "SubmissionDB", label: "store", delivery: "sync", relationship: "command", payloadKind: "command" },
    { id: "ch-queue", source: "SubmissionService", target: "JudgeQueue", label: "judge job", delivery: "async", relationship: "event", payloadKind: "event" },
    { source: "JudgeQueue", target: "JudgeWorker", label: "execute", delivery: "async", relationship: "event", payloadKind: "event" },
    { id: "ch-result", source: "JudgeWorker", target: "ResultCache", label: "store result", delivery: "sync", relationship: "command", payloadKind: "command" },
    { source: "JudgeWorker", target: "SubmissionDB", label: "persist verdict", delivery: "sync", relationship: "command", payloadKind: "command" },
    { source: "Client", target: "APIGateway", label: "poll result", delivery: "sync", relationship: "query", payloadKind: "query" },
    { source: "APIGateway", target: "ResultCache", label: "read verdict", delivery: "sync", relationship: "query", payloadKind: "query" },
  ],
  scenarios: [
    { id: "lc-submit", name: "Submit Solution", steps: [
      { name: "Submit Code", channelId: "ch-submit", fromNode: "Client", payloadType: "SubmitCode", payloadData: { problemId: "p1", lang: "python" } },
      { name: "Persist Submission", channelId: "ch-persist", fromNode: "APIGateway", payloadType: "CreateSubmission", payloadData: { id: "s1" } },
      { name: "Enqueue Judge", channelId: "ch-queue", fromNode: "SubmissionService", payloadType: "JudgeJob", payloadData: { submissionId: "s1" } },
    ]},
    { id: "lc-judge", name: "Judge Execution", steps: [
      { name: "Run in Sandbox", description: "Worker executes code against test cases", visuals: [{ kind: "highlight", targetId: "JudgeWorker", color: "yellow" }] },
      { name: "Store Result", channelId: "ch-result", fromNode: "JudgeWorker", payloadType: "JudgeResult", payloadData: { status: "Accepted" } },
    ]},
    { id: "lc-poll", name: "Poll Result", steps: [
      { name: "Client Polls", description: "Client polls result cache until ready", visuals: [{ kind: "signal", targetId: "ResultCache", color: "green" }] },
    ]},
  ],
});

export const whatsappExample = defineExample({
  id: "whatsapp",
  name: "WhatsApp",
  difficulty: "medium",
  description: "End-to-end messaging with presence, message queueing, and offline delivery.",
  tags: ["messaging", "real-time", "presence"],
  patternsUsed: ["message-queue", "websocket-gateway", "offline-inbox"],
  layoutHint: "hub",
  defaultScenarioId: "wa-send",
  columns: [
    ["SenderApp", "ReceiverApp"],
    ["MessageGateway"],
    ["ChatService", "PresenceService"],
    ["MessageDB", "OfflineQueue", "RedisPresence"],
  ],
  nodes: [
    { id: "SenderApp", kind: "external", label: "Sender App" },
    { id: "ReceiverApp", kind: "external", label: "Receiver App" },
    { id: "MessageGateway", kind: "gateway", label: "Message Gateway" },
    { id: "ChatService", kind: "service", label: "Chat Service", icon: "microservice" },
    { id: "PresenceService", kind: "service", label: "Presence Service", icon: "microservice" },
    { id: "MessageDB", kind: "database", label: "Message DB", icon: "postgres" },
    { id: "OfflineQueue", kind: "queue", label: "Offline Queue", icon: "kafka" },
    { id: "RedisPresence", kind: "database", label: "Presence", icon: "redis" },
  ],
  channels: [
    { id: "ch-send", source: "SenderApp", target: "MessageGateway", label: "send message", delivery: "sync", relationship: "command", payloadKind: "command" },
    { id: "ch-chat", source: "MessageGateway", target: "ChatService", label: "route", delivery: "sync", relationship: "command", payloadKind: "command" },
    { source: "ChatService", target: "MessageDB", label: "persist", delivery: "sync", relationship: "command", payloadKind: "command" },
    { id: "ch-presence", source: "ChatService", target: "PresenceService", label: "check online", delivery: "sync", relationship: "query", payloadKind: "query" },
    { source: "PresenceService", target: "RedisPresence", label: "lookup", delivery: "sync", relationship: "query", payloadKind: "query" },
    { id: "ch-offline", source: "ChatService", target: "OfflineQueue", label: "queue offline", delivery: "async", relationship: "event", payloadKind: "event" },
    { id: "ch-deliver", source: "MessageGateway", target: "ReceiverApp", label: "WebSocket push", delivery: "sync", relationship: "event", payloadKind: "event" },
    { source: "OfflineQueue", target: "MessageGateway", label: "drain inbox", delivery: "async", relationship: "event", payloadKind: "event" },
    { source: "ReceiverApp", target: "MessageGateway", label: "reconnect", delivery: "sync", relationship: "command", payloadKind: "command" },
  ],
  scenarios: [
    { id: "wa-send", name: "Send Message (Online)", steps: [
      { name: "Send", channelId: "ch-send", fromNode: "SenderApp", payloadType: "SendMessage", payloadData: { text: "hi" } },
      { name: "Persist", channelId: "ch-chat", fromNode: "MessageGateway", payloadType: "StoreMessage", payloadData: { chatId: "c1" } },
      { name: "Deliver", channelId: "ch-deliver", fromNode: "MessageGateway", payloadType: "PushMessage", payloadData: { text: "hi" } },
    ]},
    { id: "wa-offline", name: "Offline Delivery", steps: [
      { name: "Check Presence", channelId: "ch-presence", fromNode: "ChatService", payloadType: "IsOnline", payloadData: { userId: "u2" } },
      { name: "Queue Offline", channelId: "ch-offline", fromNode: "ChatService", payloadType: "OfflineMessage", payloadData: { userId: "u2" } },
    ]},
    { id: "wa-reconnect", name: "Reconnect Sync", steps: [
      { name: "User Online", description: "Receiver reconnects and drains offline queue", visuals: [{ kind: "signal", targetId: "ReceiverApp", color: "green" }] },
    ]},
  ],
});

export const stravaExample = defineExample({
  id: "strava",
  name: "Strava",
  difficulty: "medium",
  description: "Fitness activity tracking with GPS ingestion, leaderboards, and social feed.",
  tags: ["geo", "leaderboard", "activity-stream"],
  patternsUsed: ["event-sourcing-lite", "sorted-set-leaderboard", "activity-feed"],
  layoutHint: "tiered",
  defaultScenarioId: "strava-record",
  columns: [
    ["MobileApp"],
    ["APIGateway"],
    ["ActivityService", "LeaderboardService", "FeedService"],
    ["ActivityDB", "LeaderboardCache", "FeedQueue"],
  ],
  nodes: [
    { id: "MobileApp", kind: "external", label: "Mobile App" },
    { id: "APIGateway", kind: "gateway", label: "API Gateway" },
    { id: "ActivityService", kind: "service", label: "Activity Service", icon: "microservice" },
    { id: "LeaderboardService", kind: "service", label: "Leaderboard Service", icon: "microservice" },
    { id: "FeedService", kind: "service", label: "Feed Service", icon: "microservice" },
    { id: "ActivityDB", kind: "database", label: "Activity DB", icon: "postgres" },
    { id: "LeaderboardCache", kind: "database", label: "Leaderboard", icon: "redis" },
    { id: "FeedQueue", kind: "queue", label: "Feed Queue", icon: "kafka" },
  ],
  channels: [
    { id: "ch-upload", source: "MobileApp", target: "APIGateway", label: "upload activity", delivery: "sync", relationship: "command", payloadKind: "command" },
    { id: "ch-activity", source: "APIGateway", target: "ActivityService", label: "record", delivery: "sync", relationship: "command", payloadKind: "command" },
    { source: "ActivityService", target: "ActivityDB", label: "persist", delivery: "sync", relationship: "command", payloadKind: "command" },
    { id: "ch-board", source: "ActivityService", target: "LeaderboardService", label: "update rank", delivery: "async", relationship: "event", payloadKind: "event" },
    { source: "LeaderboardService", target: "LeaderboardCache", label: "zadd", delivery: "sync", relationship: "command", payloadKind: "command" },
    { id: "ch-feed", source: "ActivityService", target: "FeedQueue", label: "activity event", delivery: "async", relationship: "event", payloadKind: "event" },
    { source: "FeedQueue", target: "FeedService", label: "fan-out", delivery: "async", relationship: "event", payloadKind: "event" },
  ],
  scenarios: [
    { id: "strava-record", name: "Record Run", steps: [
      { name: "Upload GPS", channelId: "ch-upload", fromNode: "MobileApp", payloadType: "UploadActivity", payloadData: { distance: "10km" } },
      { name: "Store Activity", channelId: "ch-activity", fromNode: "APIGateway", payloadType: "SaveActivity", payloadData: { type: "run" } },
      { name: "Update Leaderboard", channelId: "ch-board", fromNode: "ActivityService", payloadType: "SegmentPR", payloadData: { segmentId: "s1" } },
    ]},
    { id: "strava-leaderboard", name: "View Leaderboard", steps: [
      { name: "Query Top K", description: "Fetch top athletes from sorted set", visuals: [{ kind: "signal", targetId: "LeaderboardCache", color: "green" }] },
    ]},
    { id: "strava-feed", name: "Activity Feed", steps: [
      { name: "Publish Event", channelId: "ch-feed", fromNode: "ActivityService", payloadType: "ActivityPosted", payloadData: { activityId: "a1" } },
      { name: "Fan-out Feed", visuals: [{ kind: "signal", targetId: "FeedService", color: "green" }] },
    ]},
  ],
});

export const distributedCacheExample = defineExample({
  id: "distributed-cache",
  name: "Distributed Cache",
  difficulty: "medium",
  description: "Horizontally scaled cache with consistent hashing, replication, and cache-aside reads.",
  tags: ["cache", "sharding", "consistency"],
  patternsUsed: ["consistent-hashing", "cache-aside", "replication"],
  layoutHint: "hub",
  defaultScenarioId: "dc-read",
  columns: [
    ["Client"],
    ["CacheProxy"],
    ["CacheNodeA", "CacheNodeB", "CacheNodeC"],
    ["ReplicationBus", "OriginDB"],
  ],
  nodes: [
    { id: "Client", kind: "external", label: "Client" },
    { id: "CacheProxy", kind: "gateway", label: "Cache Proxy" },
    { id: "CacheNodeA", kind: "database", label: "Cache Node A", icon: "redis" },
    { id: "CacheNodeB", kind: "database", label: "Cache Node B", icon: "redis" },
    { id: "CacheNodeC", kind: "database", label: "Cache Node C", icon: "redis" },
    { id: "OriginDB", kind: "database", label: "Origin DB", icon: "postgres" },
    { id: "ReplicationBus", kind: "queue", label: "Replication Bus", icon: "kafka" },
  ],
  channels: [
    { id: "ch-get", source: "Client", target: "CacheProxy", label: "get key", delivery: "sync", relationship: "query", payloadKind: "query" },
    { id: "ch-route", source: "CacheProxy", target: "CacheNodeA", label: "hash route", delivery: "sync", relationship: "query", payloadKind: "query" },
    { id: "ch-miss", source: "CacheProxy", target: "OriginDB", label: "cache miss", delivery: "sync", relationship: "query", payloadKind: "query" },
    { id: "ch-fill", source: "CacheProxy", target: "CacheNodeB", label: "populate", delivery: "sync", relationship: "command", payloadKind: "command" },
    { id: "ch-repl", source: "CacheNodeA", target: "ReplicationBus", label: "replicate", delivery: "async", relationship: "event", payloadKind: "event" },
    { source: "ReplicationBus", target: "CacheNodeC", label: "sync replica", delivery: "async", relationship: "event", payloadKind: "event" },
  ],
  scenarios: [
    { id: "dc-read", name: "Cache Hit", steps: [
      { name: "Get Key", channelId: "ch-get", fromNode: "Client", payloadType: "Get", payloadData: { key: "user:1" } },
      { name: "Route to Node", channelId: "ch-route", fromNode: "CacheProxy", payloadType: "HashLookup", payloadData: { key: "user:1" } },
      { name: "Return Value", visuals: [{ kind: "signal", targetId: "CacheNodeA", color: "green", label: "HIT" }] },
    ]},
    { id: "dc-miss", name: "Cache Miss", steps: [
      { name: "Miss", channelId: "ch-route", fromNode: "CacheProxy", visuals: [{ kind: "barrier", targetId: "CacheNodeA", color: "yellow", label: "MISS" }] },
      { name: "Read Origin", channelId: "ch-miss", fromNode: "CacheProxy", payloadType: "DBRead", payloadData: { key: "user:1" } },
      { name: "Populate Cache", channelId: "ch-fill", fromNode: "CacheProxy", payloadType: "CacheSet", payloadData: { key: "user:1" } },
    ]},
    { id: "dc-replicate", name: "Replication", steps: [
      { name: "Write Primary", channelId: "ch-route", fromNode: "CacheProxy", payloadType: "Set", payloadData: { key: "user:1" } },
      { name: "Async Replicate", channelId: "ch-repl", fromNode: "CacheNodeA", payloadType: "ReplicateEvent", payloadData: { key: "user:1" } },
    ]},
  ],
});

export const rateLimiterExample = defineExample({
  id: "rate-limiter",
  name: "Rate Limiter",
  difficulty: "medium",
  description: "Distributed rate limiting with token bucket, sliding window, and Redis counters.",
  tags: ["rate-limiting", "redis", "gateway"],
  patternsUsed: ["token-bucket", "sliding-window", "distributed-counter"],
  layoutHint: "pipeline",
  defaultScenarioId: "rl-allow",
  columns: [
    ["Client"],
    ["APIGateway"],
    ["RateLimiterService", "BackendService"],
    ["RedisCounter", "ConfigDB"],
  ],
  nodes: [
    { id: "Client", kind: "external", label: "Client" },
    { id: "APIGateway", kind: "gateway", label: "API Gateway" },
    { id: "RateLimiterService", kind: "service", label: "Rate Limiter", icon: "microservice" },
    { id: "RedisCounter", kind: "database", label: "Redis Counters", icon: "redis" },
    { id: "ConfigDB", kind: "database", label: "Limit Config", icon: "postgres" },
    { id: "BackendService", kind: "service", label: "Backend Service", icon: "microservice" },
  ],
  channels: [
    { id: "ch-request", source: "Client", target: "APIGateway", label: "API call", delivery: "sync", relationship: "command", payloadKind: "request" },
    { id: "ch-check", source: "APIGateway", target: "RateLimiterService", label: "check limit", delivery: "sync", relationship: "query", payloadKind: "query" },
    { id: "ch-incr", source: "RateLimiterService", target: "RedisCounter", label: "incr counter", delivery: "sync", relationship: "command", payloadKind: "command" },
    { source: "RateLimiterService", target: "ConfigDB", label: "load rules", delivery: "sync", relationship: "query", payloadKind: "query" },
    { id: "ch-forward", source: "APIGateway", target: "BackendService", label: "forward", delivery: "sync", relationship: "command", payloadKind: "command" },
  ],
  scenarios: [
    { id: "rl-allow", name: "Request Allowed", steps: [
      { name: "API Request", channelId: "ch-request", fromNode: "Client", payloadType: "APICall", payloadData: { endpoint: "/users" } },
      { name: "Check Limit", channelId: "ch-check", fromNode: "APIGateway", payloadType: "CheckRate", payloadData: { userId: "u1", limit: 100 } },
      { name: "Increment", channelId: "ch-incr", fromNode: "RateLimiterService", payloadType: "Incr", payloadData: { count: 42 } },
      { name: "Forward", channelId: "ch-forward", fromNode: "APIGateway", payloadType: "Forward", payloadData: {} },
    ]},
    { id: "rl-deny", name: "Rate Limited", steps: [
      { name: "API Request", channelId: "ch-request", fromNode: "Client", payloadType: "APICall", payloadData: { endpoint: "/users" } },
      { name: "Limit Exceeded", channelId: "ch-incr", fromNode: "RateLimiterService", visuals: [{ kind: "barrier", targetId: "RedisCounter", color: "red", label: "429" }] },
    ]},
    { id: "rl-window", name: "Sliding Window Reset", steps: [
      { name: "Window Expires", description: "Counter TTL expires and window resets", visuals: [{ kind: "lag", targetId: "RedisCounter", color: "yellow", label: "TTL reset" }] },
    ]},
  ],
});

export const onlineAuctionExample = defineExample({
  id: "online-auction",
  name: "Online Auction",
  difficulty: "medium",
  description: "Real-time bidding with optimistic locking, bid validation, and WebSocket updates.",
  tags: ["auction", "concurrency", "real-time"],
  patternsUsed: ["optimistic-locking", "websocket-push", "bid-validation"],
  layoutHint: "hub",
  defaultScenarioId: "auction-bid",
  columns: [
    ["BidderApp", "WatcherApp"],
    ["AuctionGateway"],
    ["BidService", "AuctionService"],
    ["AuctionDB", "BidCache", "EventBus"],
  ],
  nodes: [
    { id: "BidderApp", kind: "external", label: "Bidder App" },
    { id: "WatcherApp", kind: "external", label: "Watcher App" },
    { id: "AuctionGateway", kind: "gateway", label: "Auction Gateway" },
    { id: "BidService", kind: "service", label: "Bid Service", icon: "microservice" },
    { id: "AuctionService", kind: "service", label: "Auction Service", icon: "microservice" },
    { id: "AuctionDB", kind: "database", label: "Auction DB", icon: "postgres" },
    { id: "BidCache", kind: "database", label: "Current Bid", icon: "redis" },
    { id: "EventBus", kind: "queue", label: "Event Bus", icon: "kafka" },
  ],
  channels: [
    { id: "ch-bid", source: "BidderApp", target: "AuctionGateway", label: "place bid", delivery: "sync", relationship: "command", payloadKind: "command" },
    { id: "ch-validate", source: "AuctionGateway", target: "BidService", label: "validate", delivery: "sync", relationship: "command", payloadKind: "command" },
    { id: "ch-cache", source: "BidService", target: "BidCache", label: "check current", delivery: "sync", relationship: "query", payloadKind: "query" },
    { source: "BidService", target: "AuctionDB", label: "persist bid", delivery: "sync", relationship: "command", payloadKind: "command" },
    { id: "ch-event", source: "BidService", target: "EventBus", label: "bid placed", delivery: "async", relationship: "event", payloadKind: "event" },
    { source: "EventBus", target: "AuctionGateway", label: "fan-out bid", delivery: "async", relationship: "event", payloadKind: "event" },
    { id: "ch-push", source: "AuctionGateway", target: "WatcherApp", label: "price update", delivery: "sync", relationship: "event", payloadKind: "event" },
    { id: "ch-auction", source: "AuctionGateway", target: "AuctionService", label: "auction state", delivery: "sync", relationship: "query", payloadKind: "query" },
    { source: "AuctionService", target: "AuctionDB", label: "load auction", delivery: "sync", relationship: "query", payloadKind: "query" },
  ],
  scenarios: [
    { id: "auction-bid", name: "Place Bid", steps: [
      { name: "Submit Bid", channelId: "ch-bid", fromNode: "BidderApp", payloadType: "PlaceBid", payloadData: { amount: 150 } },
      { name: "Validate", channelId: "ch-validate", fromNode: "AuctionGateway", payloadType: "ValidateBid", payloadData: { minIncrement: 10 } },
      { name: "Update Cache", channelId: "ch-cache", fromNode: "BidService", payloadType: "SetCurrentBid", payloadData: { amount: 150 } },
    ]},
    { id: "auction-outbid", name: "Outbid Rejection", steps: [
      { name: "Stale Bid", channelId: "ch-bid", fromNode: "BidderApp", payloadType: "PlaceBid", payloadData: { amount: 140 } },
      { name: "Rejected", channelId: "ch-cache", fromNode: "BidService", visuals: [{ kind: "barrier", targetId: "BidCache", color: "red", label: "Outbid" }] },
    ]},
    { id: "auction-broadcast", name: "Broadcast Update", steps: [
      { name: "Publish Event", channelId: "ch-event", fromNode: "BidService", payloadType: "BidPlaced", payloadData: { amount: 150 } },
      { name: "Push to Watchers", channelId: "ch-push", fromNode: "AuctionGateway", payloadType: "PriceUpdate", payloadData: { amount: 150 } },
    ]},
  ],
});

export const youtubeExample = defineExample({
  id: "youtube",
  name: "YouTube",
  difficulty: "medium",
  description: "Video upload pipeline with transcoding, metadata storage, and CDN streaming.",
  tags: ["video", "transcoding", "cdn"],
  patternsUsed: ["async-transcoding", "blob-storage", "cdn-delivery"],
  layoutHint: "tiered",
  defaultScenarioId: "yt-upload",
  columns: [
    ["Client"],
    ["UploadGateway", "CDN"],
    ["VideoService"],
    ["ObjectStore", "MetadataDB", "TranscodeQueue"],
    ["TranscodeWorker", "ThumbnailService"],
  ],
  nodes: [
    { id: "Client", kind: "external", label: "Client" },
    { id: "CDN", kind: "gateway", label: "CDN", icon: "cdn" },
    { id: "UploadGateway", kind: "gateway", label: "Upload Gateway" },
    { id: "VideoService", kind: "service", label: "Video Service", icon: "microservice" },
    { id: "ObjectStore", kind: "database", label: "Object Store", icon: "s3" },
    { id: "MetadataDB", kind: "database", label: "Metadata DB", icon: "postgres" },
    { id: "TranscodeQueue", kind: "queue", label: "Transcode Queue", icon: "kafka" },
    { id: "TranscodeWorker", kind: "service", label: "Transcode Worker", icon: "microservice" },
    { id: "ThumbnailService", kind: "service", label: "Thumbnail Service", icon: "microservice" },
  ],
  channels: [
    { id: "ch-upload", source: "Client", target: "UploadGateway", label: "presigned URL", delivery: "sync", relationship: "command", payloadKind: "command" },
    { id: "ch-blob", source: "Client", target: "ObjectStore", label: "PUT video", delivery: "sync", relationship: "command", payloadKind: "command" },
    { id: "ch-meta", source: "UploadGateway", target: "VideoService", label: "register", delivery: "sync", relationship: "command", payloadKind: "command" },
    { source: "VideoService", target: "MetadataDB", label: "persist", delivery: "sync", relationship: "command", payloadKind: "command" },
    { id: "ch-s3-notify", source: "ObjectStore", target: "TranscodeQueue", label: "object created", delivery: "async", relationship: "event", payloadKind: "event" },
    { id: "ch-transcode", source: "VideoService", target: "TranscodeQueue", label: "transcode job", delivery: "async", relationship: "event", payloadKind: "event" },
    { source: "TranscodeQueue", target: "TranscodeWorker", label: "process", delivery: "async", relationship: "event", payloadKind: "event" },
    { source: "TranscodeWorker", target: "ObjectStore", label: "store renditions", delivery: "sync", relationship: "command", payloadKind: "command" },
    { id: "ch-thumb", source: "TranscodeWorker", target: "ThumbnailService", label: "generate thumbs", delivery: "async", relationship: "event", payloadKind: "event" },
    { source: "ThumbnailService", target: "ObjectStore", label: "store thumbs", delivery: "sync", relationship: "command", payloadKind: "command" },
    { source: "TranscodeWorker", target: "VideoService", label: "update metadata", delivery: "async", relationship: "event", payloadKind: "event" },
    { id: "ch-stream", source: "Client", target: "CDN", label: "stream", delivery: "sync", relationship: "query", payloadKind: "query" },
    { source: "CDN", target: "ObjectStore", label: "origin fetch", delivery: "sync", relationship: "query", payloadKind: "query" },
  ],
  scenarios: [
    { id: "yt-upload", name: "Upload Video", steps: [
        { name: "Request Presigned URL", channelId: "ch-upload", fromNode: "Client", payloadType: "PresignUpload", payloadData: { size: "500MB" } },
        { name: "PUT to Object Store", channelId: "ch-blob", fromNode: "Client", payloadType: "PutObject", payloadData: { key: "v1/raw.mp4" } },
        { name: "Register Metadata", channelId: "ch-meta", fromNode: "UploadGateway", payloadType: "CreateVideo", payloadData: { title: "demo" } },
    ]},
    { id: "yt-transcode", name: "Transcode", steps: [
      { name: "Enqueue Job", channelId: "ch-transcode", fromNode: "VideoService", payloadType: "TranscodeJob", payloadData: { videoId: "v1" } },
      { name: "Process", description: "Worker produces 720p/1080p renditions", visuals: [{ kind: "highlight", targetId: "TranscodeWorker", color: "yellow" }] },
    ]},
    { id: "yt-stream", name: "Stream Video", steps: [
      { name: "Play Request", channelId: "ch-stream", fromNode: "Client", payloadType: "StreamVideo", payloadData: { videoId: "v1" } },
      { name: "CDN Delivery", visuals: [{ kind: "signal", targetId: "CDN", color: "green" }] },
    ]},
  ],
});

export const jobSchedulerExample = defineExample({
  id: "job-scheduler",
  name: "Job Scheduler",
  difficulty: "medium",
  description: "Distributed cron scheduler with leader election, job queue, and worker execution.",
  tags: ["scheduler", "leader-election", "workers"],
  patternsUsed: ["leader-election", "priority-queue", "at-least-once"],
  layoutHint: "pipeline",
  defaultScenarioId: "js-schedule",
  columns: [
    ["AdminUI"],
    ["SchedulerService"],
    ["ScheduleDB", "LeaderLock", "JobQueue"],
    ["WorkerPool"],
    ["ResultStore"],
  ],
  nodes: [
    { id: "AdminUI", kind: "external", label: "Admin UI" },
    { id: "SchedulerService", kind: "service", label: "Scheduler Service", icon: "microservice" },
    { id: "ScheduleDB", kind: "database", label: "Schedule DB", icon: "postgres" },
    { id: "JobQueue", kind: "queue", label: "Job Queue", icon: "kafka" },
    { id: "LeaderLock", kind: "database", label: "Leader Lock", icon: "redis" },
    { id: "WorkerPool", kind: "service", label: "Worker Pool", icon: "microservice" },
    { id: "ResultStore", kind: "database", label: "Result Store", icon: "postgres" },
  ],
  channels: [
    { id: "ch-create", source: "AdminUI", target: "SchedulerService", label: "create job", delivery: "sync", relationship: "command", payloadKind: "command" },
    { source: "SchedulerService", target: "ScheduleDB", label: "persist", delivery: "sync", relationship: "command", payloadKind: "command" },
    { id: "ch-lock", source: "SchedulerService", target: "LeaderLock", label: "acquire leader", delivery: "sync", relationship: "command", payloadKind: "command" },
    { id: "ch-dispatch", source: "SchedulerService", target: "JobQueue", label: "dispatch", delivery: "async", relationship: "event", payloadKind: "event" },
    { source: "JobQueue", target: "WorkerPool", label: "execute", delivery: "async", relationship: "event", payloadKind: "event" },
    { id: "ch-result", source: "WorkerPool", target: "ResultStore", label: "store result", delivery: "sync", relationship: "command", payloadKind: "command" },
  ],
  scenarios: [
    { id: "js-schedule", name: "Schedule Job", steps: [
      { name: "Create Cron", channelId: "ch-create", fromNode: "AdminUI", payloadType: "CreateJob", payloadData: { cron: "0 * * * *" } },
      { name: "Persist Schedule", description: "Job definition saved to DB", visuals: [{ kind: "signal", targetId: "ScheduleDB", color: "green" }] },
    ]},
    { id: "js-dispatch", name: "Dispatch Due Job", steps: [
      { name: "Leader Tick", channelId: "ch-lock", fromNode: "SchedulerService", payloadType: "AcquireLeader", payloadData: {} },
      { name: "Enqueue Job", channelId: "ch-dispatch", fromNode: "SchedulerService", payloadType: "DispatchJob", payloadData: { jobId: "j1" } },
      { name: "Execute", description: "Worker picks up and runs job", visuals: [{ kind: "signal", targetId: "WorkerPool", color: "green" }] },
    ]},
    { id: "js-retry", name: "Retry Failed Job", steps: [
      { name: "Store Failure", channelId: "ch-result", fromNode: "WorkerPool", payloadType: "JobFailed", payloadData: { jobId: "j1" } },
      { name: "Re-enqueue", channelId: "ch-dispatch", fromNode: "SchedulerService", payloadType: "RetryJob", payloadData: { attempt: 2 } },
    ]},
  ],
});

export const fbLiveCommentsExample = defineExample({
  id: "fb-live-comments",
  name: "Facebook Live Comments",
  difficulty: "medium",
  description: "High-throughput live comment stream with WebSocket fan-out and moderation queue.",
  tags: ["real-time", "fan-out", "moderation"],
  patternsUsed: ["pub-sub", "websocket-fanout", "async-moderation"],
  layoutHint: "hub",
  defaultScenarioId: "fblc-comment",
  columns: [
    ["ViewerApp", "StreamerApp"],
    ["LiveGateway"],
    ["CommentService", "ModerationService"],
    ["CommentStream", "ModerationQueue", "LiveCache"],
  ],
  nodes: [
    { id: "ViewerApp", kind: "external", label: "Viewer App" },
    { id: "StreamerApp", kind: "external", label: "Streamer App" },
    { id: "LiveGateway", kind: "gateway", label: "Live Gateway" },
    { id: "CommentService", kind: "service", label: "Comment Service", icon: "microservice" },
    { id: "ModerationService", kind: "service", label: "Moderation Service", icon: "microservice" },
    { id: "CommentStream", kind: "queue", label: "Comment Stream", icon: "kafka" },
    { id: "ModerationQueue", kind: "queue", label: "Moderation Queue", icon: "kafka" },
    { id: "LiveCache", kind: "database", label: "Recent Comments", icon: "redis" },
  ],
  channels: [
    { id: "ch-post", source: "ViewerApp", target: "LiveGateway", label: "post comment", delivery: "sync", relationship: "command", payloadKind: "command" },
    { id: "ch-ingest", source: "LiveGateway", target: "CommentService", label: "ingest", delivery: "sync", relationship: "command", payloadKind: "command" },
    { source: "CommentService", target: "CommentStream", label: "publish", delivery: "async", relationship: "event", payloadKind: "event" },
    { source: "CommentStream", target: "LiveGateway", label: "fan-out", delivery: "async", relationship: "event", payloadKind: "event" },
    { id: "ch-mod", source: "CommentService", target: "ModerationQueue", label: "moderate", delivery: "async", relationship: "event", payloadKind: "event" },
    { source: "ModerationQueue", target: "ModerationService", label: "review", delivery: "async", relationship: "event", payloadKind: "event" },
    { id: "ch-cache", source: "CommentService", target: "LiveCache", label: "buffer", delivery: "sync", relationship: "command", payloadKind: "command" },
    { id: "ch-fanout", source: "LiveGateway", target: "StreamerApp", label: "WebSocket push", delivery: "sync", relationship: "event", payloadKind: "event" },
    { source: "LiveGateway", target: "ViewerApp", label: "WebSocket push", delivery: "sync", relationship: "event", payloadKind: "event" },
  ],
  scenarios: [
    { id: "fblc-comment", name: "Post Comment", steps: [
      { name: "Submit", channelId: "ch-post", fromNode: "ViewerApp", payloadType: "PostComment", payloadData: { text: "great stream!" } },
      { name: "Ingest", channelId: "ch-ingest", fromNode: "LiveGateway", payloadType: "IngestComment", payloadData: { streamId: "s1" } },
      { name: "Buffer", channelId: "ch-cache", fromNode: "CommentService", payloadType: "BufferComment", payloadData: {} },
    ]},
    { id: "fblc-fanout", name: "Fan-out to Viewers", steps: [
      { name: "Publish Stream", description: "Comment published to Kafka topic", visuals: [{ kind: "signal", targetId: "CommentStream", color: "green" }] },
      { name: "Push to Streamer", channelId: "ch-fanout", fromNode: "LiveGateway", payloadType: "CommentPush", payloadData: { text: "great stream!" } },
    ]},
    { id: "fblc-moderate", name: "Moderate Comment", steps: [
      { name: "Queue Review", channelId: "ch-mod", fromNode: "CommentService", payloadType: "ModerationJob", payloadData: { commentId: "c1" } },
      { name: "Auto-filter", visuals: [{ kind: "highlight", targetId: "ModerationService", color: "yellow", label: "ML filter" }] },
    ]},
  ],
});

export const newsAggregatorExample = defineExample({
  id: "news-aggregator",
  name: "News Aggregator",
  difficulty: "medium",
  description: "RSS ingestion, article deduplication, personalization, and ranked feed delivery.",
  tags: ["crawler", "dedup", "personalization"],
  patternsUsed: ["content-dedup", "inverted-index", "personalized-ranking"],
  layoutHint: "pipeline",
  defaultScenarioId: "news-ingest",
  columns: [
    ["Client"],
    ["APIGateway"],
    ["IngestService", "FeedService"],
    ["IngestQueue", "DedupCache", "ArticleDB", "SearchIndex"],
  ],
  nodes: [
    { id: "Client", kind: "external", label: "Client" },
    { id: "APIGateway", kind: "gateway", label: "API Gateway" },
    { id: "IngestService", kind: "service", label: "Ingest Service", icon: "microservice" },
    { id: "FeedService", kind: "service", label: "Feed Service", icon: "microservice" },
    { id: "ArticleDB", kind: "database", label: "Article DB", icon: "postgres" },
    { id: "SearchIndex", kind: "database", label: "Search Index", icon: "mongodb" },
    { id: "IngestQueue", kind: "queue", label: "Ingest Queue", icon: "kafka" },
    { id: "DedupCache", kind: "database", label: "Dedup Cache", icon: "redis" },
  ],
  channels: [
    { id: "ch-ingest", source: "IngestService", target: "IngestQueue", label: "new article", delivery: "async", relationship: "event", payloadKind: "event" },
    { source: "IngestQueue", target: "FeedService", label: "process", delivery: "async", relationship: "event", payloadKind: "event" },
    { id: "ch-dedup", source: "FeedService", target: "DedupCache", label: "check hash", delivery: "sync", relationship: "query", payloadKind: "query" },
    { source: "FeedService", target: "ArticleDB", label: "store", delivery: "sync", relationship: "command", payloadKind: "command" },
    { id: "ch-index", source: "FeedService", target: "SearchIndex", label: "index", delivery: "sync", relationship: "command", payloadKind: "command" },
    { id: "ch-feed", source: "Client", target: "APIGateway", label: "get feed", delivery: "sync", relationship: "query", payloadKind: "query" },
    { source: "APIGateway", target: "FeedService", label: "rank", delivery: "sync", relationship: "query", payloadKind: "query" },
  ],
  scenarios: [
    { id: "news-ingest", name: "Ingest Article", steps: [
      { name: "Crawl RSS", channelId: "ch-ingest", fromNode: "IngestService", payloadType: "NewArticle", payloadData: { url: "https://news.com/a1" } },
      { name: "Dedup Check", channelId: "ch-dedup", fromNode: "FeedService", payloadType: "CheckHash", payloadData: { hash: "abc" } },
      { name: "Index Article", channelId: "ch-index", fromNode: "FeedService", payloadType: "IndexArticle", payloadData: { id: "a1" } },
    ]},
    { id: "news-feed", name: "Personalized Feed", steps: [
      { name: "Request Feed", channelId: "ch-feed", fromNode: "Client", payloadType: "GetFeed", payloadData: { userId: "u1" } },
      { name: "Rank Articles", description: "Score by interests and recency", visuals: [{ kind: "signal", targetId: "FeedService", color: "green" }] },
    ]},
    { id: "news-dedup", name: "Duplicate Rejected", steps: [
      { name: "Duplicate Hash", channelId: "ch-dedup", fromNode: "FeedService", visuals: [{ kind: "barrier", targetId: "DedupCache", color: "yellow", label: "DUPLICATE" }] },
    ]},
  ],
});

export const priceTrackingExample = defineExample({
  id: "price-tracking",
  name: "Price Tracking",
  difficulty: "medium",
  description: "E-commerce price monitoring with scheduled crawls and alert notifications.",
  tags: ["crawler", "scheduling", "alerts"],
  patternsUsed: ["scheduled-crawl", "price-history", "threshold-alerts"],
  layoutHint: "tiered",
  defaultScenarioId: "pt-track",
  columns: [
    ["Client"],
    ["APIGateway"],
    ["TrackingService", "CrawlScheduler"],
    ["ProductDB", "PriceHistoryDB", "AlertQueue"],
    ["CrawlWorker", "NotificationService"],
  ],
  nodes: [
    { id: "Client", kind: "external", label: "Client" },
    { id: "APIGateway", kind: "gateway", label: "API Gateway" },
    { id: "TrackingService", kind: "service", label: "Tracking Service", icon: "microservice" },
    { id: "CrawlScheduler", kind: "service", label: "Crawl Scheduler", icon: "microservice" },
    { id: "ProductDB", kind: "database", label: "Product DB", icon: "postgres" },
    { id: "PriceHistoryDB", kind: "database", label: "Price History", icon: "postgres" },
    { id: "AlertQueue", kind: "queue", label: "Alert Queue", icon: "kafka" },
    { id: "CrawlWorker", kind: "service", label: "Crawl Worker", icon: "microservice" },
    { id: "NotificationService", kind: "service", label: "Notification Service", icon: "microservice" },
  ],
  channels: [
    { id: "ch-track", source: "Client", target: "APIGateway", label: "track product", delivery: "sync", relationship: "command", payloadKind: "command" },
    { source: "APIGateway", target: "TrackingService", label: "add watch", delivery: "sync", relationship: "command", payloadKind: "command" },
    { source: "TrackingService", target: "ProductDB", label: "persist", delivery: "sync", relationship: "command", payloadKind: "command" },
    { id: "ch-schedule", source: "CrawlScheduler", target: "CrawlWorker", label: "crawl job", delivery: "async", relationship: "event", payloadKind: "event" },
    { source: "CrawlScheduler", target: "ProductDB", label: "load watches", delivery: "sync", relationship: "query", payloadKind: "query" },
    { id: "ch-price", source: "CrawlWorker", target: "PriceHistoryDB", label: "record price", delivery: "sync", relationship: "command", payloadKind: "command" },
    { source: "CrawlWorker", target: "TrackingService", label: "price update", delivery: "async", relationship: "event", payloadKind: "event" },
    { id: "ch-alert", source: "TrackingService", target: "AlertQueue", label: "price drop", delivery: "async", relationship: "event", payloadKind: "event" },
    { source: "AlertQueue", target: "NotificationService", label: "notify", delivery: "async", relationship: "event", payloadKind: "event" },
  ],
  scenarios: [
    { id: "pt-track", name: "Track Product", steps: [
      { name: "Add Watch", channelId: "ch-track", fromNode: "Client", payloadType: "TrackProduct", payloadData: { url: "https://shop.com/p1", target: 29.99 } },
      { name: "Save Product", description: "Product and alert threshold stored", visuals: [{ kind: "signal", targetId: "ProductDB", color: "green" }] },
    ]},
    { id: "pt-crawl", name: "Scheduled Crawl", steps: [
      { name: "Dispatch Crawl", channelId: "ch-schedule", fromNode: "CrawlScheduler", payloadType: "CrawlJob", payloadData: { productId: "p1" } },
      { name: "Record Price", channelId: "ch-price", fromNode: "CrawlWorker", payloadType: "RecordPrice", payloadData: { price: 24.99 } },
    ]},
    { id: "pt-alert", name: "Price Drop Alert", steps: [
      { name: "Threshold Met", channelId: "ch-alert", fromNode: "TrackingService", payloadType: "PriceAlert", payloadData: { price: 24.99, target: 29.99 } },
      { name: "Notify User", visuals: [{ kind: "signal", targetId: "NotificationService", color: "green" }] },
    ]},
  ],
});

export const notificationSystemExample = defineExample({
  id: "notification-system",
  name: "Notification System",
  difficulty: "medium",
  description: "Multi-channel notifications with preference routing, templating, and delivery retries.",
  tags: ["notifications", "multi-channel", "retry"],
  patternsUsed: ["channel-router", "template-engine", "exponential-retry"],
  layoutHint: "hub",
  defaultScenarioId: "ns-send",
  columns: [
    ["ProducerService"],
    ["NotificationGateway"],
    ["RouterService", "TemplateService"],
    ["PreferenceDB", "DeliveryQueue"],
    ["EmailProvider", "PushProvider"],
  ],
  nodes: [
    { id: "ProducerService", kind: "service", label: "Producer Service", icon: "microservice" },
    { id: "NotificationGateway", kind: "gateway", label: "Notification Gateway" },
    { id: "RouterService", kind: "service", label: "Router Service", icon: "microservice" },
    { id: "TemplateService", kind: "service", label: "Template Service", icon: "microservice" },
    { id: "PreferenceDB", kind: "database", label: "Preference DB", icon: "postgres" },
    { id: "DeliveryQueue", kind: "queue", label: "Delivery Queue", icon: "kafka" },
    { id: "EmailProvider", kind: "external", label: "Email Provider" },
    { id: "PushProvider", kind: "external", label: "Push Provider" },
  ],
  channels: [
    { id: "ch-send", source: "ProducerService", target: "NotificationGateway", label: "send notification", delivery: "sync", relationship: "command", payloadKind: "command" },
    { id: "ch-route", source: "NotificationGateway", target: "RouterService", label: "route", delivery: "sync", relationship: "command", payloadKind: "command" },
    { source: "RouterService", target: "PreferenceDB", label: "load prefs", delivery: "sync", relationship: "query", payloadKind: "query" },
    { id: "ch-template", source: "RouterService", target: "TemplateService", label: "render", delivery: "sync", relationship: "query", payloadKind: "query" },
    { id: "ch-queue", source: "RouterService", target: "DeliveryQueue", label: "enqueue", delivery: "async", relationship: "event", payloadKind: "event" },
    { id: "ch-email", source: "DeliveryQueue", target: "EmailProvider", label: "send email", delivery: "async", relationship: "event", payloadKind: "event" },
    { id: "ch-push", source: "DeliveryQueue", target: "PushProvider", label: "send push", delivery: "async", relationship: "event", payloadKind: "event" },
  ],
  scenarios: [
    { id: "ns-send", name: "Send Notification", steps: [
      { name: "Trigger", channelId: "ch-send", fromNode: "ProducerService", payloadType: "Notify", payloadData: { userId: "u1", event: "order_shipped" } },
      { name: "Load Preferences", description: "User prefers push over email", visuals: [{ kind: "signal", targetId: "PreferenceDB", color: "green" }] },
      { name: "Render Template", channelId: "ch-template", fromNode: "RouterService", payloadType: "Render", payloadData: { template: "order_shipped" } },
    ]},
    { id: "ns-deliver", name: "Deliver Push", steps: [
      { name: "Enqueue", channelId: "ch-queue", fromNode: "RouterService", payloadType: "DeliveryJob", payloadData: { channel: "push" } },
      { name: "Send Push", channelId: "ch-push", fromNode: "DeliveryQueue", payloadType: "PushNotification", payloadData: { userId: "u1" } },
    ]},
    { id: "ns-retry", name: "Retry on Failure", steps: [
      { name: "Delivery Failed", channelId: "ch-email", fromNode: "DeliveryQueue", visuals: [{ kind: "barrier", targetId: "EmailProvider", color: "red", label: "FAIL" }] },
      { name: "Re-enqueue", description: "Exponential backoff retry scheduled", visuals: [{ kind: "lag", targetId: "DeliveryQueue", color: "yellow" }] },
    ]},
  ],
});

export const mediumExamples = [
  ticketmasterExample,
  instagramExample,
  fbNewsFeedExample,
  tinderExample,
  leetcodeExample,
  whatsappExample,
  stravaExample,
  distributedCacheExample,
  rateLimiterExample,
  onlineAuctionExample,
  youtubeExample,
  jobSchedulerExample,
  fbLiveCommentsExample,
  newsAggregatorExample,
  priceTrackingExample,
  notificationSystemExample,
];
